"""中文→英文疾病/症状名映射 + 症状→疾病映射

解决推荐系统核心匹配问题:
1. 前端传入中文疾病名(如"发烧")，但药物适应症是英文(如"fever")
2. 症状(如"头疼")需关联到可能的疾病(如"headache"/"migraine")才能匹配适应症
3. 中英文逗号分隔符统一处理

策略:
- 中文疾病名 → 英文标准化名 (用于适应症匹配)
- 中文症状名 → 关联英文疾病名 (用于扩展匹配范围)
- 英文疾病名也做标准化 (缩写→全称)
"""

import logging
from typing import Dict, List, Set

logger = logging.getLogger(__name__)

# ── 中文疾病名 → 英文标准化名 ──
# 涵盖常见输入: 俗名、缩写、口语描述

CHINESE_TO_ENGLISH_DISEASE: Dict[str, List[str]] = {
    "12岁及以上个体COVID-19预防": ["covid-19 prevention in individuals 12 years and older"],
    "12岁及以上高危患者轻至中度2019冠状病毒病的治疗": ["treatment of mild to moderate coronavirus disease 2019 (covid-19) in high-risk patients aged 12 years and older", "treatment of mild to moderate coronavirus disease 2019 in high-risk patients aged 12 years and older"],
    "1型和2型糖尿病": ["type 1 & 2 diabetes"],
    "1型糖尿病": ["type 1 diabetes mellitus"],
    "2型糖尿病": ["type 2 diabetes mellitus", "type 2 diabetes", "type 2 diabetes mellitus (as adjunct)"],
    "2型糖尿病伴超重": ["type 2 diabetes mellitus with overweight"],
    "2型糖尿病合并高血压患者的糖尿病肾病": ["diabetic nephropathy in patients with type 2 diabetes and hypertension"],
    "2型糖尿病患者心血管风险降低": ["cardiovascular risk reduction in type 2 diabetes"],
    "2型糖尿病的血糖控制": ["glycemic control in type 2 diabetes mellitus"],
    "5-11岁儿童COVID-19预防": ["covid-19 prevention in children 5-11 years"],
    "6个月至4岁儿童的新冠肺炎预防": ["covid-19 prevention in children 6 months to 4 years"],
    "BK病毒肾病": ["bk virus nephropathy"],
    "BRAF V600E突变甲状腺未分化癌": ["anaplastic thyroid cancer with braf v600e mutation"],
    "BRAF V600E突变非小细胞肺癌": ["non-small cell lung cancer with braf v600e mutation"],
    "BRAF V600E突变黑色素瘤": ["melanoma with braf v600e mutation"],
    "CDKL5缺乏症": ["cdkl5 deficiency disorder"],
    "COVID-19": ["covid-19 (investigational)", "covid-19"],
    "COVID-19预防": ["covid-19 prevention"],
    "Dravet综合征": ["dravet syndrome"],
    "EGFR突变非小细胞肺癌": ["non-small cell lung cancer with egfr mutations"],
    "HIV/乙型肝炎共感染": ["hiv/hepatitis b coinfection"],
    "HIV感染": ["hiv infection"],
    "HIV暴露前预防": ["pre-exposure prophylaxis for hiv"],
    "HIV暴露后预防": ["post-exposure prophylaxis for hiv", "hiv post-exposure prophylaxis"],
    "Lennox-Gastaut综合征": ["lennox-gastaut syndrome"],
    "Liddle综合征": ["liddle's syndrome"],
    "MRSA肺炎": ["mrsa pneumonia"],
    "MRSA鼻腔定植": ["mrsa nasal colonization"],
    "NSAID所致胃溃疡的预防": ["nsaid-induced gastric ulcer prophylaxis"],
    "SARS-CoV-2感染": ["sars-cov-2 infection"],
    "VRE感染": ["vre infection"],
    "β受体阻滞剂过量": ["beta-blocker overdose"],
    "三叉神经痛": ["trigeminal neuralgia"],
    "三阴性乳腺癌": ["triple-negative breast cancer"],
    "上呼吸道感染": ["upper respiratory tract infection"],
    "上运动神经元病肌痉挛": ["muscle spasticity in upper motor neuron disorders"],
    "下呼吸道感染": ["lower respiratory tract infection"],
    "下尿路症状": ["lower urinary tract symptoms"],
    "不动杆菌感染": ["acinetobacter infection"],
    "不孕症": ["infertility"],
    "不宁腿综合征": ["restless legs syndrome", "restless legs syndrome (low dose)"],
    "不适当窦性心动过速": ["inappropriate sinus tachycardia"],
    "与便秘相关的肛门疼痛": ["anal pain associated with constipation"],
    "与双相I型障碍相关的激越": ["agitation associated with bipolar i disorder"],
    "与感冒或流感症状相关的失眠": ["insomnia associated with cold or flu symptoms"],
    "与慢性肾病相关的水肿": ["edema associated with chronic kidney disease"],
    "与抑郁相关的焦虑": ["anxiety associated with depression"],
    "与疼痛相关的疲劳": ["fatigue associated with pain"],
    "与精神分裂症相关的激越": ["agitation associated with schizophrenia"],
    "与结缔组织病相关的间质性肺病": ["interstitial lung disease associated with connective tissue disease"],
    "与自闭症障碍相关的易激惹": ["irritability associated with autistic disorder"],
    "与过敏性鼻炎相关的上呼吸道症状": ["upper respiratory symptoms associated with allergic rhinitis"],
    "与过敏性鼻炎相关的鼻漏": ["rhinorrhea associated with allergic rhinitis (nasal spray)", "rhinorrhea associated with allergic rhinitis"],
    "与过敏相关的鼻窦充血": ["sinus congestion associated with allergies"],
    "丙型肝炎": ["chronic hepatitis c", "hepatitis c"],
    "丙戊酸所致肝毒性的预防": ["valproic acid-induced hepatotoxicity prophylaxis"],
    "丛集性头痛": ["cluster headache"],
    "丛集性头痛的预防": ["cluster headache prophylaxis"],
    "严重低血压": ["severe hypotension"],
    "严重低血糖": ["severe hypoglycemia"],
    "严重哮喘急性发作": ["severe asthma exacerbation"],
    "严重恶心和呕吐": ["severe nausea and vomiting"],
    "严重感染": ["serious infections"],
    "严重细菌感染": ["serious bacterial infection", "severe bacterial infection", "serious bacterial infections"],
    "严重过敏反应": ["severe allergic reactions"],
    "严重革兰氏阳性细菌感染": ["serious gram-positive bacterial infections"],
    "中度至中重度疼痛": ["moderate to moderately severe pain"],
    "中度至重度急性疼痛": ["moderate to severe acute pain", "moderate to severe acute pain (short-term)"],
    "中度至重度疼痛": ["moderate to severe pain"],
    "中度至重度阿尔茨海默病": ["moderate to severe alzheimer's disease"],
    "中心静脉导管堵塞": ["occlusion of central venous catheters"],
    "中性粒细胞减少症": ["neutropenia"],
    "中枢性尿崩症": ["central diabetes insipidus"],
    "中枢性性早熟": ["central precocious puberty"],
    "中枢神经系统成像": ["central nervous system imaging"],
    "中重度哮喘": ["moderate-to-severe asthma"],
    "中重度特应性皮炎": ["moderate-to-severe atopic dermatitis"],
    "中重度高血压": ["moderate to severe hypertension"],
    "中风预防": ["prevention of stroke"],
    "乙型/丙型肝炎": ["hepatitis b/c"],
    "乙型流感": ["influenza b"],
    "乙型流感病毒感染": ["influenza b virus infection"],
    "乙型肝炎": ["hepatitis b"],
    "乳腺炎": ["mastitis"],
    "乳腺癌": ["breast cancer", "breast cancer (hormone receptor-positive)", "breast cancer (hormone receptor-positive, her2-negative)"],
    "乳腺癌姑息治疗": ["palliative treatment of breast cancer"],
    "乳腺癌溶骨性骨转移": ["osteolytic bone metastases of breast cancer"],
    "乳腺癌芳香化酶抑制剂治疗骨丢失": ["bone loss in breast cancer on aromatase inhibitor therapy"],
    "乳腺癌辅助治疗": ["adjuvant breast cancer treatment"],
    "乳腺癌预防": ["breast cancer prevention"],
    "乳腺癌风险降低": ["breast cancer risk reduction"],
    "乳腺磁共振成像": ["breast mri"],
    "亚临床甲状腺功能减退症": ["subclinical hypothyroidism"],
    "产后出血": ["postpartum hemorrhage"],
    "产科镇痛": ["obstetric analgesia"],
    "亨廷顿病": ["huntington's disease"],
    "亨廷顿病舞蹈症": ["huntington's disease chorea"],
    "人类免疫缺陷病毒感染": ["hiv"],
    "代谢性酸中毒": ["metabolic acidosis"],
    "以入睡困难为特征的失眠症": ["insomnia characterized by difficulty with sleep onset"],
    "休克": ["shock"],
    "伤口愈合": ["wound healing"],
    "伤口感染预防": ["wound infection prophylaxis"],
    "伤寒": ["typhoid fever", "typhoid"],
    "伴严重胰岛素抵抗的1型糖尿病": ["type 1 diabetes mellitus with severe insulin resistance"],
    "伴严重胰岛素抵抗的2型糖尿病": ["type 2 diabetes mellitus with severe insulin resistance"],
    "伴有急性自杀意念或行为的重度抑郁症": ["major depressive disorder with acute suicidal ideation or behavior"],
    "伴有鼻塞的普通感冒": ["common cold with nasal congestion"],
    "低HDL所致高心血管风险": ["high cardiovascular risk with low hdl"],
    "低磷血症": ["hypophosphatemia"],
    "低血压": ["hypotension"],
    "低钙血症": ["hypocalcemia"],
    "体位性心动过速综合征": ["postural orthostatic tachycardia syndrome"],
    "体外受精": ["in vitro fertilization"],
    "体外循环抗凝": ["extracorporeal circuit anticoagulation"],
    "体癣": ["tinea corporis"],
    "体重管理": ["weight management"],
    "体重维持": ["weight loss maintenance"],
    "佝偻病": ["rickets"],
    "侵袭性曲霉病": ["invasive aspergillosis"],
    "侵袭性毛霉病": ["invasive mucormycosis"],
    "侵袭性真菌感染": ["invasive fungal infections"],
    "便秘": ["constipation"],
    "促排卵": ["ovulation induction"],
    "偏头痛": ["migraine", "migraine headache"],
    "偏头痛伴或不伴先兆": ["migraine with or without aura"],
    "偏头痛发作": ["migraine attacks"],
    "偏头痛预防": ["migraine prophylaxis", "migraine prevention"],
    "儿童慢性中重度斑块型银屑病": ["chronic moderate to severe plaque psoriasis in pediatric patients"],
    "先兆子痫": ["pre-eclampsia"],
    "先天性巨细胞病毒感染": ["congenital cytomegalovirus infection"],
    "先天性肾上腺皮质增生症": ["congenital adrenal hyperplasia"],
    "光化性角化病": ["actinic keratosis", "actinic keratosis (topical)"],
    "光损伤": ["photodamage"],
    "光老化": ["photoaging"],
    "克罗恩病": ["crohn's disease"],
    "克罗恩病累及直肠": ["crohn's disease with rectal involvement"],
    "免疫功能正常患者的水痘": ["varicella in immunocompetent patients"],
    "免疫性血小板减少性紫癜": ["immune thrombocytopenic purpura"],
    "免疫支持": ["immune support"],
    "兔热病": ["tularemia"],
    "入睡潜伏期延长": ["sleep onset latency"],
    "全身型幼年特发性关节炎": ["systemic juvenile idiopathic arthritis"],
    "全身型重症肌无力": ["generalized myasthenia gravis"],
    "全身强直阵挛发作": ["generalized tonic-clonic seizures"],
    "全身性念珠菌病": ["systemic candidiasis"],
    "全身麻醉": ["general anesthesia"],
    "全身麻醉的诱导与维持": ["induction and maintenance of general anesthesia"],
    "全面性强直-阵挛发作": ["seizure", "generalized tonic-clonic seizure"],
    "关节痛": ["pain", "joint pain"],
    "其他治疗无效的寻常痤疮": ["acne vulgaris refractory to other therapy"],
    "其他蛋白酶抑制剂的药代动力学增强剂": ["pharmacokinetic booster for other protease inhibitors"],
    "内科患者静脉血栓栓塞预防": ["venous thromboembolism prophylaxis in medical patients"],
    "内脏痉挛": ["visceral spasm"],
    "军团病": ["legionnaires' disease"],
    "冠心病一级预防": ["primary prevention of coronary heart disease"],
    "冠状动脉支架涂层": ["coronary stent coating"],
    "冠状动脉疾病": ["coronary artery disease"],
    "冷吡啉相关周期性综合征": ["cryopyrin-associated periodic syndromes"],
    "减重": ["weight loss"],
    "分化型甲状腺癌": ["differentiated thyroid carcinoma", "differentiated thyroid cancer"],
    "分娩疼痛": ["labor pain"],
    "分娩疼痛管理": ["pain management during labor"],
    "分裂情感性障碍": ["schizoaffective disorder"],
    "创伤后应激障碍": ["posttraumatic stress disorder", "post-traumatic stress disorder", "ptsd"],
    "创伤后应激障碍噩梦": ["post-traumatic stress disorder nightmares", "ptsd nightmares"],
    "创伤相关出血": ["trauma-related hemorrhage"],
    "利什曼病": ["leishmaniasis"],
    "前列腺炎": ["prostatitis"],
    "前列腺癌": ["prostate cancer"],
    "前列腺癌雄激素剥夺治疗骨丢失": ["bone loss in prostate cancer on androgen deprivation therapy"],
    "前阿片黑素细胞皮质激素原缺乏症": ["proopiomelanocortin deficiency"],
    "功能性消化不良": ["functional dyspepsia"],
    "功能性肠病": ["functional bowel disorders"],
    "功能性胃肠病": ["functional gastrointestinal disorders"],
    "动脉导管未闭": ["patent ductus arteriosus", "patent ductus arteriosus (in infants)"],
    "动脉导管未闭闭合": ["patent ductus arteriosus closure"],
    "动脉粥样硬化逆转": ["atherosclerosis regression"],
    "勃起功能障碍": ["erectile dysfunction", "erectile dysfunction (intracavernosal)"],
    "化疗引起的中性粒细胞减少症": ["chemotherapy-induced neutropenia"],
    "化疗引起的恶心与呕吐": ["chemotherapy-induced nausea and vomiting (adjunct)", "chemotherapy-induced nausea and vomiting"],
    "化疗引起的恶心呕吐": ["chemotherapy-induced nausea and vomiting", "chemotherapy-induced nausea/vomiting", "nausea and vomiting from chemotherapy", "chemotherapy-induced nausea and vomiting (refractory)"],
    "化疗引起的腹泻": ["chemotherapy-induced diarrhea"],
    "化疗相关的恶心呕吐": ["nausea and vomiting associated with chemotherapy"],
    "化脓性汗腺炎": ["hidradenitis suppurativa"],
    "化脓性链球菌咽炎": ["pharyngitis due to streptococcus pyogenes"],
    "区域麻醉": ["regional anesthesia"],
    "医院获得性肺炎": ["nosocomial pneumonia", "hospital-acquired pneumonia"],
    "十二指肠溃疡": ["duodenal ulcer"],
    "华氏巨球蛋白血症": ["waldenström's macroglobulinemia"],
    "卒中预防": ["stroke prevention"],
    "卓-艾综合征": ["zollinger-ellison syndrome"],
    "单纯性淋病": ["uncomplicated gonorrhea"],
    "单纯疱疹病毒感染": ["herpes simplex virus infection"],
    "卟啉症": ["porphyria"],
    "卡波西肉瘤": ["kaposi's sarcoma"],
    "卵巢癌": ["ovarian cancer"],
    "卵巢衰竭": ["ovarian failure"],
    "卵形疟的根治": ["radical cure of plasmodium ovale malaria"],
    "原发性": ["primary"],
    "原发性免疫缺陷": ["primary immunodeficiency"],
    "原发性全面性强直-阵挛发作": ["primary generalized tonic-clonic seizures"],
    "原发性异常β脂蛋白血症": ["primary dysbetalipoproteinemia"],
    "原发性甲状旁腺功能亢进": ["primary hyperparathyroidism"],
    "原发性痛经": ["primary dysmenorrhea"],
    "原发性肉碱缺乏症": ["primary carnitine deficiency"],
    "原发性胆汁性胆管炎": ["primary biliary cholangitis"],
    "原发性血小板增多症": ["essential thrombocythemia"],
    "原发性醛固酮增多症": ["primary hyperaldosteronism", "primary aldosteronism"],
    "原发性高脂血症": ["primary hyperlipidemia"],
    "双相I型障碍": ["bipolar i disorder", "bipolar i disorder (manic and depressive episodes)", "bipolar i disorder (manic or mixed)", "bipolar i disorder (acute)", "bipolar i disorder (manic and mixed episodes)"],
    "双相I型障碍维持治疗": ["bipolar i disorder maintenance"],
    "双相抑郁": ["bipolar depression", "bipolar depression (with olanzapine)"],
    "双相躁狂": ["bipolar mania"],
    "双相障碍": ["bipolar disorder", "bipolar disorder (manic episodes and maintenance)"],
    "发作性睡病": ["narcolepsy"],
    "发作性睡病猝倒": ["cataplexy in narcolepsy"],
    "发热": ["fever"],
    "发热性中性粒细胞减少症": ["febrile neutropenia"],
    "发热性中性粒细胞减少经验治疗": ["empiric therapy for febrile neutropenia"],
    "口咽念珠菌病": ["oropharyngeal candidiasis"],
    "口腔干燥症": ["xerostomia"],
    "口腔念珠菌病": ["oral candidiasis"],
    "口腔溃疡": ["oral ulcer"],
    "口腔疼痛": ["oral pain"],
    "口腔鹅口疮": ["oral thrush"],
    "口腔黏膜炎": ["oral mucositis"],
    "右侧感染性心内膜炎": ["right-sided infective endocarditis"],
    "叶酸缺乏": ["folate deficiency"],
    "叶酸补充": ["folate supplementation"],
    "吸入性炭疽": ["inhalational anthrax"],
    "呃逆": ["hiccups"],
    "周期性肢体运动障碍": ["periodic limb movement disorder"],
    "呼吸困难": ["dyspnea"],
    "呼吸机相关性肺炎": ["ventilator-associated pneumonia"],
    "呼吸道合胞病毒感染": ["respiratory syncytial virus infection"],
    "呼吸道感染": ["respiratory tract infection"],
    "咳嗽": ["cough"],
    "咽喉痛": ["sore throat"],
    "咽炎": ["pharyngitis"],
    "咽痛": ["pharyngeal pain"],
    "咽鼓管充血": ["eustachian tube congestion"],
    "哮吼": ["croup", "croup (nebulized)"],
    "哮喘": ["asthma"],
    "哮喘持续状态": ["status asthmaticus"],
    "哮喘预防": ["asthma prophylaxis"],
    "唇单纯疱疹": ["herpes simplex labialis"],
    "唇疱疹": ["herpes labialis", "cold sore", "herpes labialis (cold sores)"],
    "唇疱疹相关疼痛和瘙痒": ["pain and pruritus associated with cold sores"],
    "嗜酸性粒细胞增多综合征": ["hypereosinophilic syndrome"],
    "嗜酸性肉芽肿性多血管炎": ["eosinophilic granulomatosis with polyangiitis"],
    "嗜酸细胞性食管炎": ["eosinophilic esophagitis"],
    "嗜铬细胞瘤": ["pheochromocytoma"],
    "器官移植排斥反应": ["organ transplant rejection"],
    "器官移植排斥反应预防": ["organ transplant rejection prophylaxis"],
    "器官移植排斥预防": ["prophylaxis of organ transplant rejection"],
    "囊性纤维化": ["cystic fibrosis"],
    "囊性纤维化伴G551D突变或其他特定突变": ["cystic fibrosis with g551d mutation or other specified mutations"],
    "囊性纤维化相关肝病": ["cystic fibrosis-associated liver disease"],
    "回肠造口排出液减少": ["ileostomy output reduction"],
    "回肠造口高排出量管理": ["ileostomy high-output management"],
    "围手术期高血压": ["perioperative hypertension"],
    "埃博拉病毒病": ["ebola virus disease"],
    "埃尔德海姆-切斯特病": ["erdheim-chester disease"],
    "基底细胞癌": ["basal cell carcinoma (topical)", "basal cell carcinoma"],
    "增强青霉素疗效": ["enhance penicillin efficacy"],
    "复发型多发性硬化": ["relapsing forms of multiple sclerosis"],
    "复发性心包炎": ["recurrent pericarditis"],
    "复杂性区域疼痛综合征": ["complex regional pain syndrome"],
    "复杂性尿路感染": ["complicated urinary tract infection"],
    "复杂性皮肤及皮肤结构感染": ["complicated skin and skin structure infection", "complicated skin and skin structure infections"],
    "复杂性皮肤及软组织感染": ["complicated skin and soft tissue infection"],
    "复杂性皮肤感染": ["complicated skin infections"],
    "复杂性腹腔内感染": ["complicated intra-abdominal infections"],
    "复杂性腹腔感染": ["complicated intra-abdominal infection"],
    "外周动脉疾病": ["peripheral arterial disease"],
    "外周血管疾病": ["peripheral vascular disease"],
    "外耳炎": ["otitis externa"],
    "外阴阴道念珠菌病": ["vulvovaginal candidiasis"],
    "外阴阴道萎缩": ["vulvovaginal atrophy"],
    "多关节型幼年特发性关节炎": ["polyarticular juvenile idiopathic arthritis"],
    "多发性硬化": ["multiple sclerosis", "multiple sclerosis (relapsing)", "multiple sclerosis (low dose)"],
    "多发性硬化急性加重": ["acute exacerbation of multiple sclerosis", "multiple sclerosis exacerbation"],
    "多发性硬化相关疲劳": ["fatigue in multiple sclerosis"],
    "多发性骨髓瘤": ["multiple myeloma"],
    "多发性骨髓瘤溶骨性病变": ["osteolytic lesions of multiple myeloma"],
    "多囊卵巢综合征": ["polycystic ovary syndrome", "polycystic ovary syndrome (androgen excess)"],
    "多囊卵巢综合征的促排卵": ["ovulation induction in polycystic ovary syndrome"],
    "多巴反应性肌张力障碍": ["dopa-responsive dystonia"],
    "多形性胶质母细胞瘤": ["glioblastoma multiforme"],
    "多毛症": ["hirsutism"],
    "多汗症": ["hyperhidrosis"],
    "多灶性运动神经病": ["multifocal motor neuropathy"],
    "多种癌症": ["various cancers"],
    "多重耐药HIV感染": ["multidrug-resistant hiv infection"],
    "夜尿症": ["nocturia"],
    "夜间腿部痉挛": ["nocturnal leg cramps"],
    "夜间遗尿症": ["nocturnal enuresis"],
    "失眠": ["insomnia", "sleeplessness", "insomnia (short-term treatment)"],
    "失神发作": ["absence seizures", "absence seizure"],
    "头痛": ["headache"],
    "头痛伴失眠": ["headache with sleeplessness"],
    "头癣": ["tinea capitis"],
    "头皮屑": ["dandruff"],
    "头皮银屑病": ["scalp psoriasis"],
    "头虱": ["head lice"],
    "头虱病": ["pediculosis capitis"],
    "头颈癌": ["head and neck cancer"],
    "套细胞淋巴瘤": ["mantle cell lymphoma"],
    "女性型脱发": ["female pattern hair loss"],
    "女性性腺功能减退": ["female hypogonadism"],
    "妊娠剧吐": ["hyperemesis gravidarum"],
    "妊娠恶心呕吐": ["nausea and vomiting of pregnancy"],
    "妊娠期恶心呕吐": ["nausea and vomiting in pregnancy"],
    "妊娠期神经管缺陷预防": ["neural tube defect prevention in pregnancy"],
    "妊娠期高血压": ["hypertension in pregnancy"],
    "妊娠期高血压危象": ["hypertensive crisis in pregnancy"],
    "妊娠滋养细胞肿瘤": ["gestational trophoblastic neoplasia"],
    "妊娠相关恶心": ["pregnancy-related nausea"],
    "妊娠高血压": ["pregnancy-induced hypertension"],
    "威尔逊病": ["wilson's disease"],
    "婴儿痉挛症": ["infantile spasm"],
    "婴儿肠绞痛": ["infantile colic"],
    "婴幼儿孤独症": ["infantile autism"],
    "子宫内膜增生预防": ["endometrial hyperplasia prevention"],
    "子宫内膜异位症": ["endometriosis"],
    "子宫内膜炎": ["endometritis"],
    "子宫内膜癌": ["endometrial cancer"],
    "子宫平滑肌瘤": ["uterine leiomyomata"],
    "子宫收缩乏力": ["uterine atony"],
    "子宫肌瘤": ["uterine fibroids"],
    "子痫": ["eclampsia"],
    "子痫前期/子痫": ["preeclampsia/eclampsia"],
    "季节性情感障碍": ["seasonal affective disorder"],
    "孤独症相关易激惹": ["irritability in autism"],
    "实体瘤骨转移": ["bone metastases from solid tumors"],
    "室上性心动过速": ["supraventricular tachycardia"],
    "室性心动过速": ["ventricular tachycardia"],
    "室性心律失常": ["ventricular arrhythmias", "ventricular arrhythmia"],
    "宫颈成熟与引产": ["cervical ripening and labor induction"],
    "宫颈癌": ["cervical cancer"],
    "家族性地中海热": ["familial mediterranean fever"],
    "家族性腺瘤性息肉病": ["familial adenomatous polyposis"],
    "寄生虫感染": ["parasitic infection", "parasitic infections"],
    "寄生虫蠕虫感染": ["parasitic worm infections"],
    "对标准泻药无反应的阿片类药物引起的便秘": ["opioid-induced constipation not responsive to standard laxatives"],
    "对阿昔洛韦耐药的单纯疱疹病毒感染": ["herpes simplex virus infection resistant to acyclovir"],
    "寻常痤疮": ["acne vulgaris", "acne vulgaris (topical)"],
    "导尿用尿道麻醉": ["urethral anesthesia for catheterization"],
    "射血分数保留的心力衰竭": ["heart failure with preserved ejection fraction"],
    "射血分数降低的心力衰竭": ["heart failure with reduced ejection fraction", "heart failure with reduced ejection fraction (to reduce hospitalizations)"],
    "小于胎龄儿生长迟缓": ["sga infants with growth failure"],
    "小伤口感染预防": ["minor wound infection prophylaxis"],
    "小皮肤手术": ["minor skin procedure"],
    "小细胞肺癌": ["small cell lung cancer"],
    "小肠细菌过度生长": ["small intestinal bacterial overgrowth"],
    "小袋虫病": ["balantidiasis"],
    "尖锐湿疣": ["condylomata acuminata"],
    "尤文肉瘤": ["ewing's sarcoma"],
    "尿失禁": ["urinary incontinence"],
    "尿崩症": ["diabetes insipidus"],
    "尿布疹": ["diaper rash"],
    "尿布疹伴可疑感染": ["diaper rash with suspected infection"],
    "尿布皮炎并发念珠菌感染": ["diaper dermatitis complicated by candida"],
    "尿急": ["urinary urgency"],
    "尿液碱化": ["urinary alkalinization", "urine alkalinization"],
    "尿液酸化": ["urinary acidification"],
    "尿潴留": ["urinary retention"],
    "尿路上皮癌": ["urothelial carcinoma"],
    "尿路感染": ["bacterial urinary tract infection", "urinary tract infection"],
    "尿路感染预防": ["urinary tract infection prophylaxis"],
    "尿路疼痛": ["urinary tract pain"],
    "尿道炎": ["urethritis"],
    "尿频": ["urinary frequency"],
    "局灶性发作": ["focal seizures"],
    "局灶性癫痫发作": ["focal seizure"],
    "局部/区域麻醉": ["local / regional anesthesia"],
    "局部皮肤感染": ["topical skin infections"],
    "局部皮肤病": ["topical dermatologic conditions"],
    "局部麻醉": ["local anesthesia"],
    "屋尘螨致过敏性鼻炎伴或不伴结膜炎": ["house dust mite-induced allergic rhinitis with or without conjunctivitis"],
    "屋尘螨过敏性鼻炎": ["allergic rhinitis due to house dust mites"],
    "川崎病": ["kawasaki disease"],
    "巨噬细胞活化综合征": ["macrophage activation syndrome"],
    "巨幼细胞性贫血": ["megaloblastic anemia"],
    "巨细胞动脉炎": ["giant cell arteritis"],
    "巨细胞病毒感染": ["cytomegalovirus retinitis", "cytomegalovirus", "cmv infection", "cytomegalovirus infection (investigational)", "cytomegalovirus infection"],
    "巨细胞病毒结肠炎": ["cytomegalovirus colitis"],
    "巨细胞病毒肺炎": ["cytomegalovirus pneumonitis"],
    "已确诊的动脉粥样硬化性心血管疾病": ["established atherosclerotic cardiovascular disease"],
    "巴德-毕德氏综合征": ["bardet-biedl syndrome"],
    "巴贝虫病": ["babesiosis"],
    "布鲁氏菌病": ["brucellosis"],
    "帕金森病": ["parkinson's disease", "parkinson's disease (in combination with levodopa)", "parkinson's disease (adjunct to levodopa)"],
    "帕金森病痴呆": ["parkinson's disease dementia"],
    "帕金森病精神病": ["parkinson's disease psychosis"],
    "帕金森综合征": ["parkinsonism"],
    "带状疱疹": ["herpes zoster", "shingles"],
    "带状疱疹后神经痛": ["postherpetic neuralgia", "postherpetic neuralgia (topical patch)"],
    "干燥症": ["xerosis"],
    "干燥综合征": ["sjögren's syndrome", "sjogren's syndrome"],
    "干眼症": ["dry eye"],
    "幼年特发性关节炎": ["juvenile idiopathic arthritis"],
    "幽门螺杆菌根除": ["h. pylori eradication", "helicobacter pylori eradication (adjunctive)", "helicobacter pylori eradication", "h. pylori eradication (part of regimen)"],
    "广泛性焦虑障碍": ["generalized anxiety disorder"],
    "库欣病": ["cushing's disease"],
    "库欣综合征": ["cushing's syndrome"],
    "应激性溃疡预防": ["stress ulcer prophylaxis"],
    "延缓临床1型糖尿病发病": ["delay onset of clinical type 1 diabetes mellitus"],
    "开角型青光眼": ["open-angle glaucoma"],
    "异位妊娠": ["ectopic pregnancy"],
    "异常子宫出血": ["abnormal uterine bleeding"],
    "弓形虫病": ["toxoplasmosis"],
    "引产": ["labor induction"],
    "弥散性血管内凝血": ["disseminated intravascular coagulation"],
    "弥漫性大B细胞淋巴瘤": ["diffuse large b-cell lymphoma"],
    "强直-阵挛发作": ["tonic-clonic seizures"],
    "强直性脊柱炎": ["ankylosing spondylitis"],
    "强迫症": ["obsessive-compulsive disorder", "ocd"],
    "心内膜炎": ["endocarditis"],
    "心内膜炎预防": ["endocarditis prophylaxis"],
    "心内膜炎预防与治疗": ["endocarditis prophylaxis and treatment"],
    "心力衰竭": ["heart failure", "heart failure (with nitrates)", "heart failure (adjunct)"],
    "心力衰竭所致水肿": ["edema due to heart failure"],
    "心力衰竭相关水肿": ["edema associated with heart failure"],
    "心动过缓": ["bradycardia (if pacing ineffective)", "bradycardia"],
    "心包炎": ["pericarditis"],
    "心室颤动": ["ventricular fibrillation"],
    "心律失常": ["arrhythmia", "arrhythmias"],
    "心房扑动": ["atrial flutter"],
    "心房扑动心室率控制": ["atrial flutter rate control"],
    "心房扑动转复窦性心律": ["atrial flutter conversion to sinus rhythm"],
    "心房颤动": ["atrial fibrillation", "atrial fibrillation (bridge therapy)"],
    "心房颤动/扑动": ["atrial fibrillation/flutter"],
    "心房颤动心率控制": ["atrial fibrillation rate control"],
    "心房颤动转复窦性心律": ["atrial fibrillation conversion to sinus rhythm"],
    "心源性休克": ["cardiogenic shock"],
    "心绞痛": ["angina pectoris", "angina"],
    "心绞痛预防": ["angina pectoris prophylaxis"],
    "心肌梗死": ["myocardial infarction"],
    "心肌梗死后": ["post-mi", "post-myocardial infarction"],
    "心肌梗死后左心室功能障碍": ["left ventricular dysfunction after myocardial infarction"],
    "心肌梗死预防": ["myocardial infarction prophylaxis", "prevention of myocardial infarction"],
    "心肺复苏": ["cardiopulmonary resuscitation"],
    "心脏骤停": ["cardiac arrest"],
    "心血管事件的一级预防": ["primary prevention of cardiovascular events"],
    "心血管事件预防": ["prevention of cardiovascular events", "cardiovascular event prevention"],
    "心血管事件风险降低": ["cardiovascular event risk reduction (in combination with statin)", "cardiovascular event risk reduction"],
    "心血管疾病二级预防": ["secondary prevention of cardiovascular disease"],
    "心血管疾病预防": ["prevention of cardiovascular disease"],
    "志贺菌病": ["shigellosis"],
    "快速眼动睡眠行为障碍": ["rem sleep behavior disorder"],
    "念珠菌病": ["candidiasis", "candidiasis (topical)"],
    "念珠菌血症": ["candidemia"],
    "念珠菌血症与侵袭性念珠菌病": ["candidemia and invasive candidiasis"],
    "怀疑细菌或真菌感染的湿疹": ["eczema with suspected bacterial or fungal infection"],
    "急性中耳炎": ["otitis media"],
    "急性冠状动脉综合征": ["acute coronary syndrome"],
    "急性失代偿性心力衰竭": ["acute decompensated heart failure (short-term)", "acute decompensated heart failure"],
    "急性心绞痛": ["acute angina pectoris"],
    "急性心肌梗死": ["acute myocardial infarction"],
    "急性早幼粒细胞白血病": ["acute promyelocytic leukemia"],
    "急性淋巴细胞白血病": ["acute lymphoblastic leukemia", "acute lymphoblastic leukemia (philadelphia chromosome-positive)"],
    "急性疼痛": ["acute pain"],
    "急性痛风": ["acute gout"],
    "急性痛风发作": ["acute gout flares"],
    "急性痛风性关节炎": ["acute gouty arthritis"],
    "急性白血病": ["leukemia", "acute leukemia"],
    "急性精神病性激越": ["acute psychotic agitation"],
    "急性细菌性皮肤及皮肤结构感染": ["acute bacterial skin and skin structure infection", "acute bacterial skin and skin structure infections"],
    "急性细菌性鼻窦炎": ["acute bacterial sinusitis"],
    "急性结肠假性梗阻": ["acute colonic pseudo-obstruction"],
    "急性缺血性卒中": ["acute ischemic stroke"],
    "急性肌肉疼痛": ["acute muscle pain"],
    "急性肌肉痉挛": ["acute muscle spasm"],
    "急性肌肉骨骼疼痛": ["acute musculoskeletal pain"],
    "急性肾损伤": ["acute kidney injury"],
    "急性脊髓损伤": ["spinal cord injury (acute)", "spinal cord injury"],
    "急性腹泻": ["acute diarrhea"],
    "急性膀胱炎": ["acute cystitis"],
    "急性辐射综合征造血亚综合征": ["hematopoietic subsyndrome of acute radiation syndrome"],
    "急性过敏反应": ["acute allergic reaction"],
    "急性酒精戒断": ["acute alcohol withdrawal"],
    "急性铁中毒": ["acute iron intoxication"],
    "急性非特异性腹泻": ["acute nonspecific diarrhea"],
    "急性髓系白血病": ["acute myeloid leukemia", "acute myeloid leukemia (part of conditioning)", "acute myeloid leukemia (palliative)"],
    "急性鼻窦炎": ["acute sinusitis"],
    "性别肯定激素治疗": ["gender-affirming hormone therapy"],
    "性早熟": ["precocious puberty"],
    "性欲低下": ["low libido"],
    "性腺功能减退症": ["hypogonadism"],
    "恶心和呕吐": ["nausea", "nausea and vomiting"],
    "恶性淋巴瘤": ["malignant lymphoma"],
    "恶性肿瘤相关性高钙血症": ["hypercalcemia of malignancy"],
    "恶性高热": ["malignant hyperthermia"],
    "恶病质": ["cachexia"],
    "惊恐障碍": ["panic disorder"],
    "感冒症状": ["cold symptoms"],
    "感冒相关咳嗽": ["cough associated with cold"],
    "感染性休克": ["septic shock"],
    "感染性心内膜炎": ["infective endocarditis"],
    "感染性腹泻": ["infectious diarrhea"],
    "慢性乙型肝炎": ["chronic hepatitis b"],
    "慢性乙型肝炎感染": ["chronic hepatitis b infection"],
    "慢性偏头痛": ["chronic migraine"],
    "慢性单纯性苔藓": ["lichen simplex chronicus"],
    "慢性心绞痛": ["chronic angina"],
    "慢性心绞痛预防": ["chronic angina prophylaxis"],
    "慢性支气管炎急性加重": ["acute exacerbation of chronic bronchitis"],
    "慢性淋巴细胞白血病": ["chronic lymphocytic leukemia"],
    "慢性炎性脱髓鞘性多发性神经病": ["chronic inflammatory demyelinating polyneuropathy"],
    "慢性牙周炎": ["chronic periodontitis"],
    "慢性特发性荨麻疹": ["chronic idiopathic urticaria"],
    "慢性疼痛": ["chronic pain"],
    "慢性移植物抗宿主病": ["chronic graft-versus-host disease"],
    "慢性稳定型心绞痛": ["chronic stable angina"],
    "慢性细菌性前列腺炎": ["chronic bacterial prostatitis"],
    "慢性肉芽肿病": ["chronic granulomatous disease"],
    "慢性肾病贫血": ["anemia of chronic kidney disease"],
    "慢性肾脏病": ["chronic kidney disease"],
    "慢性肾脏病相关高磷血症": ["hyperphosphatemia in ckd"],
    "慢性肾脏病高磷血症": ["hyperphosphatemia in chronic kidney disease"],
    "慢性肾衰竭低钙血症": ["hypocalcemia in chronic renal failure"],
    "慢性肾衰竭高磷血症": ["hyperphosphatemia in chronic renal failure"],
    "慢性腹泻": ["chronic diarrhea"],
    "慢性荨麻疹": ["chronic urticaria"],
    "慢性阻塞性肺疾病": ["chronic obstructive pulmonary disease", "copd"],
    "慢性静脉功能不全": ["chronic venous insufficiency"],
    "慢性颈部和背部疼痛": ["chronic neck and back pain"],
    "慢性髓系白血病": ["chronic myeloid leukemia"],
    "慢性鼻窦炎伴鼻息肉": ["chronic rhinosinusitis with nasal polyps", "chronic rhinosinusitis with nasal polyposis"],
    "憩室病": ["diverticulosis"],
    "成骨不全症": ["osteogenesis imperfecta"],
    "戒烟": ["smoking cessation"],
    "房颤": ["atrial fibrillation (if warfarin unsuitable)", "atrial fibrillation"],
    "房颤伴栓塞": ["atrial fibrillation with embolization"],
    "房颤卒中预防": ["stroke prevention in atrial fibrillation", "atrial fibrillation stroke prevention (bridge therapy)", "atrial fibrillation stroke prevention"],
    "扁平苔藓": ["lichen planus"],
    "扁桃体炎": ["tonsillitis"],
    "手术中瞳孔缩小抑制": ["miosis inhibition during surgery (ophthalmic)", "miosis inhibition during surgery"],
    "手术前镇静": ["sedation before procedures"],
    "手术期间抗凝": ["anticoagulation during surgery"],
    "手术部位感染预防": ["surgical site infection prophylaxis"],
    "手术预防": ["surgical prophylaxis"],
    "打喷嚏": ["sneezing"],
    "抑郁": ["depression"],
    "抗中性粒细胞胞浆抗体相关性血管炎": ["antineutrophil cytoplasmic antibody-associated vasculitis"],
    "抗抑郁药所致性功能障碍": ["sexual dysfunction from antidepressants"],
    "抗生素相关性腹泻": ["antibiotic-associated diarrhea"],
    "抗磷脂综合征": ["antiphospholipid syndrome"],
    "抗酸": ["antacid"],
    "抽动秽语综合征": ["tourette's syndrome", "tourette's disorder", "tourette syndrome"],
    "拉伤或扭伤相关肌肉痉挛": ["muscle spasm associated with strains or sprains"],
    "择期手术术前贫血": ["preoperative anemia in elective surgery"],
    "持续性偏头痛": ["hemicrania continua"],
    "指甲软化": ["nail softening"],
    "排便费力": ["straining during defecation"],
    "排尿困难": ["dysuria"],
    "排痰性咳嗽": ["productive cough"],
    "接受抗逆转录病毒治疗的HIV患者的非感染性腹泻": ["non-infectious diarrhea in hiv patients on antiretroviral therapy"],
    "接触性皮炎": ["contact dermatitis"],
    "接触性皮炎伴可疑感染": ["contact dermatitis with suspected infection"],
    "摇头丸中毒": ["ecstasy intoxication"],
    "操作前麻醉": ["pre-procedural anesthesia"],
    "支持治疗": ["supportive"],
    "支架植入术后冠状动脉疾病预防": ["coronary artery disease prevention after stent implantation"],
    "支架血栓形成预防": ["prevention of stent thrombosis"],
    "支气管扩张": ["bronchiectasis"],
    "支气管炎": ["acute bacterial exacerbation of chronic bronchitis"],
    "支气管痉挛": ["bronchospasm"],
    "放射性恶心呕吐": ["radiation-induced nausea and vomiting"],
    "斑块状银屑病": ["plaque psoriasis"],
    "斑秃": ["alopecia areata", "alopecia areata (topical)"],
    "斜视": ["strabismus"],
    "新型冠状病毒感染": ["covid-19"],
    "新生儿呼吸暂停": ["neonatal apnea"],
    "新生儿戒断综合征": ["neonatal abstinence syndrome"],
    "旅行者腹泻的预防": ["traveler's diarrhea prevention"],
    "无并发症的皮肤感染": ["uncomplicated skin infection"],
    "无排卵性女性不孕症": ["female infertility due to anovulation"],
    "无烟烟草戒断": ["smokeless tobacco cessation"],
    "无症状左心室功能不全": ["asymptomatic left ventricular dysfunction"],
    "无症状肺曲霉病": ["asymptomatic pulmonary aspergillosis"],
    "早产": ["preterm labor", "preterm labor (tocolysis)"],
    "早产儿呼吸暂停": ["apnea of prematurity"],
    "早产胎儿肺成熟": ["preterm labor fetal lung maturation"],
    "春季角结膜炎": ["vernal keratoconjunctivitis"],
    "显微镜下结肠炎": ["microscopic colitis"],
    "晕动病": ["motion sickness"],
    "晚期前列腺癌": ["advanced prostate cancer"],
    "晚期卵巢癌": ["advanced ovarian carcinoma"],
    "晚期疾病中的呼吸困难": ["dyspnea in advanced disease"],
    "普拉德-威利综合征": ["prader-willi syndrome"],
    "普通感冒": ["common cold"],
    "普通感冒症状": ["common cold symptoms"],
    "暴食症": ["binge eating disorder"],
    "更年期症状": ["menopause symptoms"],
    "月经性偏头痛": ["menstrual migraine"],
    "月经过多": ["heavy menstrual bleeding", "menorrhagia"],
    "术前肠道准备": ["bowel preparation before surgery"],
    "术前镇静": ["preoperative sedation"],
    "术后恶心呕吐": ["postoperative nausea and vomiting"],
    "术后疼痛": ["postoperative pain"],
    "术后肠梗阻": ["postoperative ileus"],
    "术后静脉血栓栓塞的预防": ["prevention of venous thromboembolism after surgery"],
    "术后高血压": ["postoperative hypertension"],
    "机械心脏瓣膜": ["mechanical heart valve"],
    "杂合子家族性高胆固醇血症": ["heterozygous familial hypercholesterolemia"],
    "格雷夫斯病": ["graves' disease"],
    "梅尼埃病": ["meniere's disease"],
    "梅毒": ["syphilis"],
    "横纹肌肉瘤": ["rhabdomyosarcoma"],
    "毛周角化病": ["keratosis pilaris"],
    "毛细胞白血病": ["hairy cell leukemia"],
    "毛霉病": ["mucormycosis"],
    "水痘": ["chickenpox"],
    "水痘-带状疱疹病毒感染": ["varicella zoster virus infection"],
    "水痘预防": ["prevention of varicella"],
    "水肿": ["edema"],
    "汞中毒": ["mercury poisoning"],
    "沙眼": ["trachoma"],
    "沙眼衣原体感染": ["chlamydia trachomatis infection"],
    "沙门氏菌病": ["salmonellosis"],
    "泌乳失败": ["lactation failure"],
    "注意缺陷多动障碍": ["attention deficit hyperactivity disorder", "adhd"],
    "流感治疗": ["influenza treatment"],
    "流感预防": ["influenza prophylaxis"],
    "流涕": ["runny nose"],
    "流行性感冒": ["influenza"],
    "浅表皮肤感染": ["superficial skin infection"],
    "消化不良": ["dyspepsia"],
    "消化性溃疡": ["peptic ulcer disease"],
    "消化性溃疡出血": ["peptic ulcer bleeding"],
    "液体维持": ["fluid maintenance"],
    "淋巴瘤": ["lymphoma", "lymphomas"],
    "淋巴管平滑肌瘤病": ["lymphangioleiomyomatosis"],
    "淋病": ["gonorrhea"],
    "深静脉血栓形成": ["deep vein thrombosis"],
    "深静脉血栓治疗": ["deep vein thrombosis treatment", "treatment of deep vein thrombosis"],
    "深静脉血栓预防": ["deep vein thrombosis prophylaxis"],
    "混合型血脂异常": ["mixed dyslipidemia"],
    "湿疹": ["eczema"],
    "湿疹相关瘙痒": ["pruritus associated with eczema"],
    "溃疡性直肠乙状结肠炎": ["ulcerative proctosigmoiditis"],
    "溃疡性直肠炎": ["ulcerative proctitis"],
    "溃疡性结肠炎": ["ulcerative colitis"],
    "滑囊炎": ["bursitis"],
    "滤泡性淋巴瘤": ["follicular lymphoma"],
    "滴虫病": ["trichomoniasis"],
    "潜伏性结核": ["latent tuberculosis"],
    "潜伏性结核感染": ["latent tuberculosis infection"],
    "潮热": ["hot flashes"],
    "激素替代": ["hormone replacement"],
    "激素替代疗法": ["hormone replacement therapy"],
    "激越": ["agitation"],
    "炎性疾病": ["inflammatory conditions"],
    "炎性眼病": ["inflammatory eye conditions"],
    "炎症": ["inflammation"],
    "炎症性皮肤病": ["inflammatory skin conditions", "inflammatory skin conditions (topical)"],
    "炎症性肠病": ["inflammatory bowel disease", "inflammatory bowel disease (crohn's disease, ulcerative colitis)"],
    "炎症性肠病相关慢性腹泻": ["chronic diarrhea associated with inflammatory bowel disease"],
    "炭疽": ["anthrax"],
    "炭疽预防": ["anthrax prophylaxis"],
    "烟酸缺乏": ["pellagra"],
    "烟酸缺乏症": ["niacin deficiency"],
    "热痉挛": ["heat cramps"],
    "焦虑": ["anxiety"],
    "焦虑症状": ["anxiety symptoms"],
    "焦虑障碍": ["anxiety disorders"],
    "牙周炎": ["periodontitis"],
    "牙痛": ["toothache"],
    "牙科感染": ["dental infection"],
    "特发性肺纤维化": ["idiopathic pulmonary fibrosis"],
    "特发性身材矮小": ["idiopathic short stature"],
    "特发性震颤": ["essential tremor"],
    "特应性皮炎": ["atopic dermatitis"],
    "特纳综合征": ["turner syndrome"],
    "狼疮": ["lupus"],
    "狼疮性肾炎": ["lupus nephritis"],
    "猝倒症": ["cataplexy"],
    "玫瑰痤疮": ["rosacea", "acne rosacea"],
    "生殖器单纯疱疹": ["genital herpes simplex"],
    "生殖器疱疹": ["genital herpes", "herpes genitalis"],
    "生殖细胞肿瘤": ["germ cell tumors"],
    "生长激素缺乏症": ["growth hormone deficiency"],
    "甲型流感": ["influenza a"],
    "甲型流感病毒感染": ["influenza a virus infection"],
    "甲氨蝶呤毒性降低": ["methotrexate toxicity reduction"],
    "甲状旁腺功能亢进": ["hyperparathyroidism"],
    "甲状旁腺功能减退症": ["hypoparathyroidism"],
    "甲状旁腺癌的高钙血症": ["hypercalcemia of parathyroid carcinoma"],
    "甲状腺功能亢进": ["hyperthyroidism"],
    "甲状腺功能减退症": ["hypothyroidism"],
    "甲状腺危象": ["thyroid storm"],
    "甲状腺抑制试验": ["thyroid suppression test"],
    "甲状腺激素替代治疗用于甲状腺肿或甲状腺癌": ["thyroid hormone replacement in goiter or thyroid cancer"],
    "甲状腺癌": ["thyroid cancer (tsh suppression)", "thyroid cancer"],
    "甲状腺肿": ["goiter"],
    "甲状腺髓样癌": ["medullary thyroid cancer"],
    "甲癣": ["onychomycosis"],
    "男性不育症": ["male infertility (oligospermia)", "male infertility"],
    "男性乳房发育症": ["gynecomastia"],
    "疖病": ["furunculosis"],
    "疟疾": ["malaria"],
    "疟疾治疗": ["malaria treatment"],
    "疟疾的预防和治疗": ["malaria prophylaxis and treatment"],
    "疟疾预防": ["malaria prophylaxis"],
    "疟疾预防和治疗": ["malaria prevention and treatment"],
    "疥疮": ["scabies", "scabies (topical/oral)"],
    "疱疹样皮炎": ["dermatitis herpetiformis"],
    "疲劳": ["fatigue"],
    "疼痛伴失眠": ["pain with associated sleeplessness"],
    "疼痛管理": ["pain management"],
    "病毒性出血热": ["viral hemorrhagic fever"],
    "病毒感染": ["viral infection"],
    "病理性高分泌状态": ["pathological hypersecretory conditions"],
    "痔疮": ["hemorrhoids"],
    "痛经": ["dysmenorrhea"],
    "痛风": ["gout"],
    "痛风发作": ["gout flares"],
    "痛风性关节炎": ["gouty arthritis"],
    "痛风预防": ["gout prophylaxis"],
    "痤疮": ["acne"],
    "痤疮瘢痕": ["acne scarring"],
    "痴呆": ["dementia"],
    "痴呆相关激越": ["agitation in dementia"],
    "瘙痒": ["pruritus"],
    "瘢痕疙瘩": ["keloids"],
    "瘦素受体缺乏症": ["leptin receptor deficiency"],
    "癌性爆发痛": ["breakthrough cancer pain"],
    "癌性疼痛": ["cancer pain"],
    "癌症化疗引起的恶心呕吐": ["cancer chemotherapy-induced nausea and vomiting"],
    "癌症患者化疗所致贫血": ["anemia due to chemotherapy in cancer patients"],
    "癫痫": ["epilepsy", "seizure disorders"],
    "癫痫发作": ["seizures", "seizures (when oral phenytoin not possible)", "seizures (focal and generalized)"],
    "癫痫持续状态": ["status epilepticus"],
    "白喉": ["diphtheria"],
    "白癜风": ["vitiligo", "vitiligo (with puva therapy)"],
    "白细胞介素-1受体拮抗剂缺乏症": ["interleukin-1 receptor antagonist deficiency"],
    "白血病": ["leukemias"],
    "百日咳": ["pertussis"],
    "皮肤T细胞淋巴瘤": ["cutaneous t-cell lymphoma"],
    "皮肤利什曼病": ["cutaneous leishmaniasis"],
    "皮肤及软组织感染": ["skin and soft tissue infection"],
    "皮肤和软组织感染": ["skin and soft tissue infection (methicillin-sensitive staph aureus)", "skin and soft tissue infection (mrsa)", "skin and soft tissue infection", "skin and soft tissue infection"],
    "皮肤干燥": ["dry skin"],
    "皮肤念珠菌病": ["cutaneous candidiasis"],
    "皮肤感染": ["skin infection", "skin infections"],
    "皮肤感染预防": ["skin infection prophylaxis (topical)", "skin infection prophylaxis"],
    "皮肤疾病": ["dermatologic conditions"],
    "皮肤病": ["dermatoses"],
    "皮肤瘙痒": ["skin itching"],
    "皮肤癌": ["skin cancer"],
    "皮肤癌预防": ["skin cancer prevention"],
    "皮肤真菌感染": ["fungal skin infection", "fungal infections of skin"],
    "皮肤黏膜单纯疱疹病毒感染": ["mucocutaneous herpes simplex virus infection"],
    "盆腔炎性疾病": ["pelvic inflammatory disease"],
    "盘尾丝虫病": ["onchocerciasis"],
    "盘状红斑狼疮": ["discoid lupus erythematosus"],
    "直立性低血压": ["orthostatic hypotension"],
    "直肠炎": ["proctitis"],
    "真性红细胞增多症": ["polycythemia vera"],
    "真菌性指甲感染": ["fungal nail infections"],
    "真菌性皮肤感染": ["fungal skin infections"],
    "真菌性角膜炎": ["fungal keratitis"],
    "真菌感染": ["fungal infections"],
    "眩晕": ["vertigo"],
    "眼睑痉挛": ["blepharospasm"],
    "眼睫状肌麻痹": ["ocular cycloplegia"],
    "眼部感染": ["ocular infections (topical)", "ocular infections"],
    "睑缘炎": ["blepharitis"],
    "睡眠呼吸暂停": ["sleep apnea"],
    "睡眠维持障碍": ["sleep maintenance"],
    "睫状肌麻痹": ["cycloplegia"],
    "睾丸癌": ["testicular cancer"],
    "瞳孔散大": ["mydriasis"],
    "矮小同源盒基因缺陷症": ["short stature homeobox gene deficiency"],
    "矮小症": ["short stature"],
    "破伤风": ["tetanus", "tetanus (adjunct)"],
    "砷中毒": ["arsenic poisoning"],
    "硬化性苔藓": ["lichen sclerosus"],
    "硬皮病": ["scleroderma"],
    "硬皮病肾危象": ["scleroderma renal crisis"],
    "硬纤维瘤": ["desmoid tumor", "desmoid tumors"],
    "硬脊膜穿刺后头痛": ["post-dural puncture headache"],
    "硬膜外麻醉": ["epidural anesthesia"],
    "磁共振血管造影": ["magnetic resonance angiography"],
    "磁共振造影": ["mri contrast"],
    "磁共振造影剂": ["mri contrast agent"],
    "社交恐惧症": ["social phobia"],
    "社交焦虑障碍": ["social anxiety disorder"],
    "社区获得性肺炎": ["community-acquired pneumonia"],
    "祛痰": ["expectorant"],
    "神经囊尾蚴病": ["neurocysticercosis"],
    "神经外科癫痫预防": ["neurosurgical seizure prophylaxis"],
    "神经性贪食症": ["bulimia nervosa"],
    "神经母细胞瘤": ["neuroblastoma"],
    "神经源性膀胱": ["neurogenic bladder"],
    "神经源性逼尿肌过度活动": ["neurogenic detrusor overactivity"],
    "神经病理性疼痛": ["neuropathic pain"],
    "神经痛": ["nerve pain"],
    "神经管缺陷预防": ["prevention of neural tube defects"],
    "神经肌肉阻滞逆转": ["reversal of neuromuscular blockade"],
    "神经阻滞剂恶性综合征": ["neuroleptic malignant syndrome"],
    "禽流感": ["avian influenza"],
    "移植中巨细胞病毒预防": ["cytomegalovirus prophylaxis"],
    "移植受者巨细胞病毒感染": ["cytomegalovirus infection in transplant recipients"],
    "移植后巨细胞病毒预防": ["cytomegalovirus prophylaxis in transplant"],
    "移植患者巨细胞病毒预防": ["cytomegalovirus prophylaxis in transplant patients"],
    "移植排斥预防": ["transplant rejection prophylaxis"],
    "移植物抗宿主病": ["graft-versus-host disease"],
    "程序性镇静": ["procedural sedation"],
    "稳定型冠状动脉疾病": ["stable coronary artery disease"],
    "稳定型心绞痛": ["stable angina"],
    "立克次体感染": ["rickettsial infection", "rickettsial infections"],
    "类癌": ["carcinoid tumors"],
    "类风湿关节炎": ["rheumatoid arthritis"],
    "类风湿关节炎疼痛": ["rheumatoid arthritis pain"],
    "粘液性水肿昏迷": ["myxedema coma"],
    "粪便嵌塞": ["fecal impaction"],
    "粪类圆线虫病": ["strongyloidiasis"],
    "精神分裂症": ["schizophrenia", "schizophrenia (adjunctive therapy)"],
    "精神分裂症或分裂情感性障碍中的自杀行为": ["suicidal behavior in schizophrenia or schizoaffective disorder"],
    "精神病性抑郁症": ["psychotic depression"],
    "精神病性障碍": ["psychotic disorders"],
    "糖尿病": ["diabetes", "gestational diabetes mellitus"],
    "糖尿病周围神经病变": ["diabetic peripheral neuropathy"],
    "糖尿病神经病变": ["diabetic neuropathy"],
    "糖尿病神经病变疼痛": ["diabetic neuropathy pain"],
    "糖尿病肾病": ["diabetic nephropathy", "diabetic kidney disease"],
    "糖尿病视网膜病变": ["diabetic retinopathy"],
    "糖尿病酮症酸中毒": ["diabetic ketoacidosis"],
    "糖皮质激素性骨质疏松": ["glucocorticoid-induced osteoporosis"],
    "糖皮质激素诱发的骨质疏松症": ["corticosteroid-induced osteoporosis"],
    "糜烂性食管炎": ["erosive esophagitis"],
    "系统性硬化症指端溃疡": ["systemic sclerosis digital ulcers"],
    "系统性红斑狼疮": ["systemic lupus erythematosus"],
    "系统性肥大细胞增多症": ["systemic mastocytosis"],
    "紧张性头痛": ["tension headache"],
    "紧张性头痛的辅助治疗": ["adjunct in tension headache"],
    "纤维肌痛": ["fibromyalgia", "fibromyalgia (low dose)"],
    "纯合子家族性高胆固醇血症": ["homozygous familial hypercholesterolemia"],
    "组织胞浆菌病": ["histoplasmosis"],
    "细胞因子释放综合征": ["cytokine release syndrome"],
    "细菌性皮肤感染": ["bacterial skin infection", "bacterial skin infections"],
    "细菌性结膜炎": ["bacterial conjunctivitis (ophthalmic)", "bacterial conjunctivitis"],
    "细菌性脑膜炎": ["bacterial meningitis"],
    "细菌性脓毒症": ["bacterial sepsis"],
    "细菌性阴道病": ["bacterial vaginosis", "bacterial vaginosis (topical)"],
    "细菌感染": ["bacterial infection", "bacterial infections"],
    "细菌感染的辅助治疗": ["adjunctive therapy for bacterial infections"],
    "终末期肾病相关高磷血症": ["hyperphosphatemia in end-stage renal disease"],
    "经典型霍奇金淋巴瘤": ["classical hodgkin lymphoma"],
    "经前烦躁障碍": ["premenstrual dysphoric disorder"],
    "经前烦躁障碍症": ["pmdd"],
    "经期疼痛": ["menstrual pain"],
    "经皮冠状动脉介入治疗": ["percutaneous coronary intervention"],
    "经皮冠状动脉介入治疗期间抗凝": ["anticoagulation during percutaneous coronary intervention"],
    "结核病": ["tuberculosis", "tuberculosis (latent infection)", "tuberculosis (active, in combination)", "tuberculosis (second-line)"],
    "结直肠癌": ["colorectal cancer"],
    "结肠镜检查前肠道准备": ["bowel preparation before colonoscopy"],
    "结膜充血缓解": ["conjunctival decongestant"],
    "结膜炎": ["bacterial conjunctivitis", "conjunctivitis", "conjunctivitis (topical)", "conjunctivitis (ophthalmic)"],
    "结节性痒疹": ["prurigo nodularis"],
    "结节性硬化症": ["tuberous sclerosis complex"],
    "结节性硬化症相关癫痫发作": ["tuberous sclerosis complex-associated seizures"],
    "绝经后妇女骨质疏松预防/治疗": ["osteoporosis prevention/treatment in postmenopausal women"],
    "绝经后骨质疏松": ["postmenopausal osteoporosis"],
    "绝经期潮热": ["menopausal hot flashes"],
    "绝经期症状": ["menopausal symptoms"],
    "绝经期血管舒缩症状": ["menopausal vasomotor symptoms"],
    "绦虫感染": ["tapeworm infection"],
    "绦虫病": ["taeniasis"],
    "继发性卒中预防": ["secondary stroke prevention"],
    "继发性闭经": ["secondary amenorrhea"],
    "继发感染的外伤性皮肤损伤": ["secondarily infected traumatic skin lesions"],
    "继发感染的皮肤病变": ["secondarily infected skin lesions"],
    "维生素D缺乏": ["vitamin d deficiency"],
    "维生素E缺乏症": ["vitamin e deficiency"],
    "维生素缺乏": ["vitamin deficiency"],
    "缓解由过敏或普通感冒引起的鼻塞": ["relief of nasal congestion due to allergies or common cold"],
    "缺铁性贫血": ["iron deficiency anemia"],
    "耐万古霉素屎肠球菌感染": ["vancomycin-resistant enterococcus faecium infections", "vancomycin-resistant enterococcus faecium infection"],
    "耐万古霉素肠球菌感染": ["vancomycin-resistant enterococci infection"],
    "耐多药结核病": ["multidrug-resistant tuberculosis"],
    "耐甲氧西林金黄色葡萄球菌去定植": ["mrsa decolonization"],
    "耐甲氧西林金黄色葡萄球菌感染": ["mrsa infection"],
    "耳道湿疹": ["eczema of the ear canal"],
    "耶氏肺孢子菌肺炎": ["pneumocystis jirovecii pneumonia"],
    "肉瘤": ["sarcomas", "sarcoma"],
    "肉碱缺乏": ["carnitine deficiency"],
    "肌张力障碍": ["dystonia"],
    "肌肉疼痛": ["muscle pain"],
    "肌肉痉挛": ["muscle spasm", "muscle spasms"],
    "肌肉痉挛状态": ["muscle spasticity"],
    "肌肉骨骼疼痛": ["musculoskeletal pain"],
    "肌萎缩侧索硬化": ["amyotrophic lateral sclerosis"],
    "肌阵挛发作": ["myoclonic seizures"],
    "肌阵挛性发作": ["myoclonic seizure"],
    "肛裂": ["anal fissure", "anal fissures", "anal fissure (topical)"],
    "肛门瘙痒": ["pruritus ani", "anal pruritus"],
    "肛门癌": ["anal cancer"],
    "肝吸虫感染": ["liver fluke infection"],
    "肝性脑病": ["hepatic encephalopathy"],
    "肝癌": ["liver cancer"],
    "肝硬化相关水肿": ["edema associated with liver cirrhosis", "edema associated with hepatic cirrhosis"],
    "肝素过量": ["heparin overdose"],
    "肝素逆转": ["heparin reversal"],
    "肝细胞癌": ["hepatocellular carcinoma"],
    "肝脏疾病所致水肿": ["edema due to hepatic disease"],
    "肠易激综合征": ["irritable bowel syndrome", "irritable bowel syndrome (fiber supplement)"],
    "肠绞痛": ["intestinal colic"],
    "肠道准备": ["bowel preparation"],
    "肠道念珠菌病": ["intestinal candidiasis (non-systemic)", "intestinal candidiasis"],
    "肠阿米巴病": ["intestinal amebiasis"],
    "股癣": ["tinea cruris"],
    "肢端肥大症": ["acromegaly"],
    "肥大细胞增多症": ["mastocytosis"],
    "肥胖": ["obesity"],
    "肥胖症": ["obesity (short-term adjunct)", "obesity"],
    "肥胖管理": ["obesity management"],
    "肺动脉高压": ["pulmonary arterial hypertension"],
    "肺孢子菌肺炎": ["pneumocystis pneumonia", "pneumocystis pneumonia (adjunct)"],
    "肺孢子菌肺炎预防": ["pneumocystis pneumonia prophylaxis"],
    "肺栓塞": ["pulmonary embolism"],
    "肺栓塞治疗": ["pulmonary embolism treatment", "treatment of pulmonary embolism"],
    "肺炎": ["pneumonia"],
    "肾上腺功能不全": ["adrenal insufficiency"],
    "肾上腺皮质癌": ["adrenocortical carcinoma"],
    "肾性尿崩症": ["nephrogenic diabetes insipidus"],
    "肾母细胞瘤": ["wilms tumor", "wilms' tumor"],
    "肾病相关水肿": ["edema associated with renal disease"],
    "肾病综合征": ["nephrotic syndrome"],
    "肾病综合征相关水肿": ["edema associated with nephrotic syndrome"],
    "肾盂肾炎": ["pyelonephritis"],
    "肾细胞癌": ["renal cell carcinoma"],
    "肾结石": ["kidney stones (uric acid)", "kidney stones"],
    "肾结石排出": ["kidney stone expulsion"],
    "肾结石预防": ["nephrolithiasis prevention", "nephrolithiasis prophylaxis", "kidney stone prevention"],
    "肾绞痛": ["renal colic"],
    "肾脏疾病所致水肿": ["edema due to renal disease"],
    "肾衰竭铝中毒": ["aluminum toxicity in renal failure"],
    "肿瘤溶解综合征": ["tumor lysis syndrome"],
    "肿瘤溶解综合征预防": ["tumor lysis syndrome prophylaxis"],
    "肿瘤溶解综合征预防/化疗患者高尿酸血症": ["tumor lysis syndrome prophylaxis/hyperuricemia in chemotherapy patients"],
    "胃溃疡": ["gastric ulcer", "stomach ulcer"],
    "胃灼热": ["heartburn"],
    "胃痛": ["stomach pain"],
    "胃癌": ["gastric cancer", "stomach cancer"],
    "胃肠炎呕吐": ["gastroenteritis vomiting"],
    "胃肠胀气": ["flatulence"],
    "胃肠道憩室炎": ["diverticulitis of gastrointestinal tract"],
    "胃肠道痉挛": ["gi spasms"],
    "胃肠道间质瘤": ["gastrointestinal stromal tumor", "gist"],
    "胃腺癌": ["gastric adenocarcinoma"],
    "胃轻瘫": ["gastroparesis"],
    "胃酸反流": ["acid reflux"],
    "胃酸消化不良": ["acid indigestion"],
    "胃食管反流病": ["gastroesophageal reflux disease"],
    "胆汁酸吸收不良性腹泻": ["bile acid malabsorption diarrhea"],
    "胆结石": ["biliary calculus"],
    "胆结石溶解": ["gallstone dissolution"],
    "胆绞痛": ["biliary colic"],
    "背痛": ["back pain"],
    "胰腺癌": ["pancreatic cancer"],
    "胰腺神经内分泌肿瘤": ["pancreatic neuroendocrine tumors", "pancreatic neuroendocrine tumor"],
    "胰腺腺癌": ["adenocarcinoma of pancreas", "pancreatic adenocarcinoma"],
    "胱氨酸尿症": ["cystinuria"],
    "胶质母细胞瘤": ["glioblastoma"],
    "胸闷": ["chest congestion"],
    "胼胝": ["calluses"],
    "脂溢性皮炎": ["seborrheic dermatitis"],
    "脑卒中": ["stroke"],
    "脑水肿": ["cerebral edema"],
    "脑肿瘤": ["brain tumors", "brain tumor", "brain tumors (primary and metastatic)"],
    "脑膜炎": ["meningitis"],
    "脑膜炎球菌携带状态": ["meningococcal carrier state"],
    "脑膜炎球菌病": ["meningococcal disease"],
    "脑血管痉挛": ["cerebral vasospasm"],
    "脓毒症": ["sepsis"],
    "脓疱疮": ["impetigo"],
    "脓胸": ["empyema"],
    "脱发": ["hair loss"],
    "脱水": ["dehydration"],
    "腹泻": ["traveler's diarrhea", "diarrhea", "diarrhea (short-term)"],
    "腹泻型肠易激综合征": ["irritable bowel syndrome with diarrhea"],
    "腹泻或呕吐所致电解质失衡": ["electrolyte imbalance due to diarrhea or vomiting"],
    "腹腔内感染": ["intra-abdominal infection"],
    "腹膜炎": ["peritonitis"],
    "膀胱不适": ["bladder discomfort"],
    "膀胱炎": ["cystitis"],
    "膀胱痉挛": ["bladder spasm"],
    "膀胱癌": ["bladder cancer", "bladder cancer (intravesical)"],
    "膀胱过度活动症": ["overactive bladder"],
    "自身免疫性溶血性贫血": ["autoimmune hemolytic anemia"],
    "自身免疫性疾病": ["autoimmune disorders"],
    "良性前列腺增生": ["benign prostatic hyperplasia", "bph"],
    "艰难梭菌感染": ["clostridium difficile infection", "clostridioides difficile infection"],
    "艰难梭菌结肠炎": ["clostridioides difficile colitis"],
    "艾滋病相关卡波西肉瘤": ["aids-related kaposi's sarcoma"],
    "花斑癣": ["tinea versicolor"],
    "芽生菌病": ["blastomycosis"],
    "苯二氮卓类药物过量": ["benzodiazepine overdose"],
    "草花粉致过敏性鼻炎伴或不伴结膜炎": ["grass pollen-induced allergic rhinitis with or without conjunctivitis"],
    "草花粉过敏性鼻炎": ["allergic rhinitis due to grass pollen"],
    "荨麻疹": ["urticaria", "urticaria (adjunct)", "hives"],
    "药代动力学增强剂": ["pharmacokinetic booster"],
    "药物引起的锥体外系症状": ["drug-induced extrapyramidal symptoms"],
    "药物流产": ["medical abortion (with mifepristone)", "medical abortion"],
    "莱姆病": ["lyme disease", "lyme disease (early stage)"],
    "菌血症": ["bacteremia"],
    "葡萄球菌性人工瓣膜心内膜炎": ["staphylococcal prosthetic valve endocarditis"],
    "葡萄球菌性小肠结肠炎": ["staphylococcal enterocolitis"],
    "葡萄膜炎": ["uveitis"],
    "虫咬": ["insect bites", "insect bite"],
    "虱病": ["pediculosis", "lice"],
    "虹膜炎": ["iritis"],
    "蛔虫病": ["ascariasis"],
    "蛛网膜下腔出血后血管痉挛": ["vasospasm after subarachnoid hemorrhage"],
    "蛛网膜下腔出血后血管痉挛的预防": ["prevention of vasospasm after subarachnoid hemorrhage"],
    "血友病A": ["hemophilia a (mild)", "hemophilia a"],
    "血友病短期预防出血": ["short-term prevention of bleeding in hemophilia"],
    "血吸虫病": ["schistosomiasis"],
    "血栓栓塞的预防": ["prevention of thromboembolism"],
    "血栓栓塞的预防/治疗": ["thromboembolism prevention/treatment"],
    "血液透析中的继发性肉碱缺乏": ["secondary carnitine deficiency in hemodialysis"],
    "血清素综合征": ["serotonin syndrome"],
    "血管性痴呆": ["vascular dementia"],
    "血管性血友病": ["von willebrand disease (type 1)", "von willebrand disease"],
    "血管扩张性休克": ["vasodilatory shock"],
    "血管活性肠肽瘤": ["vasoactive intestinal peptide tumors"],
    "血管炎": ["vasculitis"],
    "血管痉挛": ["vasospasm"],
    "血管痉挛性心绞痛": ["vasospastic angina"],
    "血管运动性鼻炎": ["vasomotor rhinitis"],
    "血管迷走性晕厥": ["vasovagal syncope"],
    "血脂异常": ["dyslipidemia"],
    "衣原体感染": ["chlamydia infection"],
    "补钙": ["calcium supplementation"],
    "表演焦虑": ["performance anxiety"],
    "表面麻醉": ["topical anesthesia"],
    "视神经脊髓炎谱系疾病": ["neuromyelitis optica spectrum disorder"],
    "角化过度": ["hyperkeratosis"],
    "角膜炎": ["keratitis"],
    "诱导泌乳": ["lactation induction"],
    "诺卡菌病": ["nocardiosis"],
    "谷固醇血症": ["sitosterolemia"],
    "豚草花粉过敏性鼻炎": ["allergic rhinitis due to ragweed pollen"],
    "贝赫切特病": ["behçet's disease"],
    "败血症": ["septicemia"],
    "贪食症": ["bulimia"],
    "贫血": ["anemia"],
    "贾第鞭毛虫引起的腹泻": ["diarrhea caused by giardia"],
    "贾第鞭毛虫病": ["giardiasis"],
    "超重伴有体重相关合并症": ["overweight with weight-related comorbidities"],
    "足癣": ["tinea pedis"],
    "跟腱炎": ["achilles tendonitis"],
    "路易体痴呆": ["lewy body dementia"],
    "转移性去势敏感性前列腺癌": ["metastatic castration-sensitive prostate cancer"],
    "转移性结直肠癌": ["metastatic colorectal cancer"],
    "转移性黑色素瘤": ["metastatic melanoma"],
    "轮班工作睡眠障碍": ["shift work sleep disorder"],
    "软组织肉瘤": ["soft tissue sarcoma"],
    "轻度关节炎": ["minor arthritis"],
    "轻度烧伤": ["minor burns"],
    "轻度皮肤刺激": ["minor skin irritation"],
    "轻度肌肉关节疼痛": ["minor muscle and joint pain"],
    "轻度至中度溃疡性结肠炎": ["mild to moderate ulcerative colitis"],
    "轻微疼痛": ["minor aches and pains"],
    "输尿管结石": ["ureteral stones"],
    "输血所致慢性铁过载": ["chronic iron overload due to transfusions"],
    "输血相关慢性铁过载": ["chronic iron overload due to blood transfusions"],
    "边缘区淋巴瘤": ["marginal zone lymphoma"],
    "边缘型人格障碍": ["borderline personality disorder"],
    "过敏": ["allergy"],
    "过敏反应": ["allergic reactions"],
    "过敏反应辅助治疗": ["allergic reaction adjuvant therapy"],
    "过敏性接触性皮炎": ["allergic contact dermatitis"],
    "过敏性疾病": ["allergic disorders", "allergic conditions"],
    "过敏性结膜炎": ["allergic conjunctivitis"],
    "过敏性鼻炎": ["allergic rhinitis"],
    "过敏性鼻炎伴鼻塞": ["allergic rhinitis with nasal congestion"],
    "过敏症": ["anaphylaxis"],
    "运动中能量补充": ["energy replenishment during sports"],
    "运动诱发性支气管痉挛": ["exercise-induced bronchospasm"],
    "近期卒中": ["recent stroke"],
    "近期心肌梗死": ["recent myocardial infarction"],
    "迟发性运动障碍": ["tardive dyskinesia"],
    "逆转肝素抗凝作用": ["reversal of heparin anticoagulation"],
    "透析患者继发性甲状旁腺功能亢进": ["secondary hyperparathyroidism"],
    "造血干细胞移植前预处理": ["conditioning before hematopoietic stem cell transplantation"],
    "遗传性血管性水肿": ["hereditary angioedema"],
    "遗尿症": ["bedwetting"],
    "避孕": ["contraception", "contraception (implant)"],
    "部分性发作": ["partial seizures (adjunct)", "partial seizures"],
    "部分性发作癫痫": ["partial onset seizures"],
    "部分性癫痫发作": ["partial seizures"],
    "酒渣鼻": ["rosacea (topical)", "rosacea"],
    "酒渣鼻面部红斑": ["facial erythema of rosacea", "facial erythema of rosacea (topical)"],
    "酒精使用障碍": ["alcohol use disorder"],
    "酒精性肝炎": ["alcoholic hepatitis"],
    "酒精戒断": ["alcohol withdrawal"],
    "酒精戒断综合征": ["alcohol withdrawal syndrome"],
    "酵母菌感染": ["yeast infection"],
    "重度哮喘": ["severe asthma with eosinophilic phenotype", "severe asthma"],
    "重度嗜酸粒细胞性哮喘": ["severe eosinophilic asthma"],
    "重度治疗经历的HIV感染": ["heavily treatment-experienced hiv infection"],
    "重度甲状腺功能减退": ["severe hypothyroidism"],
    "重度结节性痤疮": ["severe nodular acne"],
    "重度胃食管反流病": ["severe gastroesophageal reflux disease"],
    "重度顽固性皮肤癣菌病": ["severe recalcitrant dermatophytosis"],
    "重性抑郁障碍": ["major depressive disorder", "major depressive disorder (adjunct)", "major depressive disorder (augmentation)", "major depressive disorder (adjunctive therapy)"],
    "重性抑郁障碍的辅助治疗": ["adjunctive therapy in major depression"],
    "重性抑郁障碍辅助治疗": ["adjunctive treatment for major depressive disorder"],
    "重症COVID-19": ["covid-19 (severe)", "covid-19"],
    "重症监护室镇静": ["sedation in intensive care unit"],
    "重症肌无力": ["myasthenia gravis"],
    "重金属中毒": ["heavy metal poisoning"],
    "金黄色葡萄球菌菌血症": ["staphylococcus aureus bacteremia"],
    "钙缺乏": ["calcium deficiency"],
    "钙通道阻滞剂过量": ["calcium channel blocker overdose"],
    "钩虫感染": ["hookworm infection"],
    "铁补充": ["iron supplementation"],
    "铁过载": ["iron overload"],
    "铅中毒": ["lead poisoning"],
    "铜绿假单胞菌感染": ["pseudomonas aeruginosa infection"],
    "铬缺乏症": ["chromium deficiency"],
    "银屑病": ["psoriasis", "psoriasis (topical)", "psoriasis (face/groin)", "psoriasis (with puva therapy)"],
    "银屑病关节炎": ["psoriatic arthritis"],
    "链球菌咽炎": ["streptococcal pharyngitis"],
    "链球菌感染": ["streptococcal infection", "streptococcal infections"],
    "镁缺乏": ["magnesium deficiency"],
    "镇咳": ["cough suppression"],
    "镇痛": ["analgesia"],
    "镇静": ["sedation"],
    "镇静作用的逆转": ["reversal of conscious sedation"],
    "镰状细胞贫血": ["sickle cell anemia"],
    "长期体重管理": ["chronic weight management"],
    "门静脉高压症": ["portal hypertension"],
    "闭经": ["amenorrhea"],
    "间变性星形细胞瘤": ["anaplastic astrocytoma"],
    "间日疟的根治": ["radical cure of plasmodium vivax malaria"],
    "间歇性跛行": ["intermittent claudication"],
    "间质性膀胱炎": ["interstitial cystitis"],
    "阴虱病": ["pediculosis pubis"],
    "阴道念珠菌病": ["vaginal candidiasis"],
    "阴道萎缩": ["vaginal atrophy"],
    "阴道酵母菌感染": ["vaginal yeast infection"],
    "阵发性室上性心动过速": ["paroxysmal supraventricular tachycardia"],
    "阵发性房颤/房扑": ["paroxysmal atrial fibrillation/flutter"],
    "阵发性睡眠性血红蛋白尿症": ["paroxysmal nocturnal hemoglobinuria"],
    "阻塞性睡眠呼吸暂停引起的嗜睡": ["obstructive sleep apnea", "sleepiness due to obstructive sleep apnea"],
    "阿尔茨海默病": ["alzheimer's disease", "alzheimer disease", "alzheimer disease (mild cognitive impairment or mild dementia stage)"],
    "阿昔洛韦耐药单纯疱疹病毒感染": ["acyclovir-resistant hsv infections"],
    "阿片使用障碍复吸预防": ["opioid use disorder relapse prevention"],
    "阿片类药物使用障碍": ["opioid use disorder"],
    "阿片类药物引起的便秘": ["opioid-induced constipation"],
    "阿片类药物引起的呼吸抑制": ["respiratory depression from opioids"],
    "阿片类药物引起的瘙痒": ["pruritus due to opioids"],
    "阿片类药物戒断": ["opioid withdrawal"],
    "阿片类药物过量": ["opioid overdose"],
    "阿片类药物过量预防": ["opioid overdose prevention"],
    "阿米巴病": ["amebiasis"],
    "降低心血管风险": ["cardiovascular risk reduction"],
    "隐孢子虫或贾第鞭毛虫引起的腹泻": ["diarrhea caused by cryptosporidium"],
    "隐孢子虫病": ["cryptosporidiosis"],
    "隐球菌性脑膜炎": ["cryptococcal meningitis"],
    "隐球菌病": ["cryptococcosis (maintenance, non-meningeal)", "cryptococcosis"],
    "隐睾症": ["cryptorchidism"],
    "难治性侵袭性曲霉病": ["invasive aspergillosis refractory to other therapy"],
    "难治性失眠": ["refractory insomnia"],
    "难治性抑郁症": ["treatment-resistant depression", "treatment-resistant depression (augmentation)", "refractory depression (augmentation)", "refractory depression"],
    "难治性癫痫持续状态": ["refractory status epilepticus"],
    "难治性精神分裂症": ["treatment-resistant schizophrenia"],
    "难治性部分性癫痫发作": ["refractory partial seizures"],
    "难治性高血压": ["hypertension (refractory)", "hypertension"],
    "雄激素性脱发": ["androgenetic alopecia", "androgenetic alopecia (topical)"],
    "雌激素过低": ["hypoestrogenism"],
    "雷诺现象": ["raynaud's phenomenon"],
    "需吸氧的新型冠状病毒肺炎": ["covid-19 requiring oxygen"],
    "霍奇金淋巴瘤": ["hodgkin's lymphoma", "hodgkin lymphoma"],
    "青光眼": ["glaucoma"],
    "青春期延迟": ["delayed puberty"],
    "静脉性腿部溃疡": ["venous leg ulcers"],
    "静脉血栓栓塞治疗": ["venous thromboembolism treatment"],
    "静脉血栓栓塞预防": ["prevention of venous thromboembolism", "venous thromboembolism prophylaxis"],
    "静脉血栓栓塞预防与治疗": ["vte prophylaxis and treatment"],
    "非典型溶血性尿毒症综合征": ["atypical hemolytic uremic syndrome"],
    "非去极化神经肌肉阻滞剂的逆转": ["reversal of nondepolarizing neuromuscular blockers"],
    "非去极化神经肌肉阻滞的逆转": ["reversal of nondepolarizing neuromuscular blockade"],
    "非复杂性尿路感染": ["uncomplicated urinary tract infection"],
    "非小细胞肺癌": ["lung cancer", "non-small cell lung cancer"],
    "非洲锥虫病": ["african trypanosomiasis"],
    "非瓣膜性房颤卒中预防": ["stroke prevention in non-valvular atrial fibrillation"],
    "非甾体抗炎药所致溃疡的预防": ["nsaid-induced ulcer prevention"],
    "非甾体抗炎药相关性溃疡的预防": ["nsaid-induced ulcer prophylaxis"],
    "非转移性去势抵抗性前列腺癌": ["non-metastatic castration-resistant prostate cancer"],
    "非输血依赖性地中海贫血伴铁过载": ["non-transfusion-dependent thalassemia with iron overload"],
    "非过敏性鼻炎": ["non-allergic rhinitis"],
    "非酒精性脂肪性肝炎": ["nonalcoholic steatohepatitis", "non-alcoholic steatohepatitis"],
    "非酒精性脂肪性肝病": ["non-alcoholic fatty liver disease"],
    "非霍奇金淋巴瘤": ["non-hodgkin's lymphoma", "non-hodgkin lymphoma"],
    "革兰氏阴性菌感染": ["gram-negative bacterial infection"],
    "鞭虫病": ["trichuriasis"],
    "预防/治疗产后出血": ["prevent/treat postpartum hemorrhage"],
    "预防2019冠状病毒病": ["prevention of coronavirus disease 2019 (covid-19)", "prevention of coronavirus disease 2019"],
    "预防HIV母婴传播": ["prevention of mother-to-child transmission of hiv"],
    "预防和治疗产后出血": ["prevention and treatment of postpartum hemorrhage"],
    "预防复发性早产": ["recurrent preterm birth prevention"],
    "预防子宫内膜增生": ["prevention of endometrial hyperplasia"],
    "预防尿酸肾结石": ["prevention of uric acid kidney stones"],
    "预防支架内再狭窄": ["prevention of in-stent restenosis"],
    "预防脑血管意外": ["prevention of cerebrovascular accident"],
    "预防运动诱发的支气管痉挛": ["prevention of exercise-induced bronchospasm"],
    "预防非甾体抗炎药引起的溃疡": ["prevention of nsaid-induced ulcers"],
    "预防非甾体抗炎药引起的胃溃疡": ["prevention of nsaid-induced gastric ulcers"],
    "颅内压增高": ["elevated intracranial pressure"],
    "颅内高压": ["intracranial hypertension"],
    "颈肌张力障碍": ["cervical dystonia"],
    "风湿性疾病": ["rheumatic disorders"],
    "风湿热": ["rheumatic fever"],
    "风湿热预防": ["rheumatic fever prophylaxis"],
    "食欲减退": ["appetite loss"],
    "食欲刺激": ["appetite stimulation"],
    "食物过敏预防": ["food allergy prophylaxis"],
    "食管念珠菌病": ["esophageal candidiasis"],
    "食管炎": ["esophagitis"],
    "食管癌": ["esophageal cancer"],
    "食管静脉曲张出血": ["esophageal variceal bleeding", "esophageal varices bleeding"],
    "食管食物嵌顿": ["esophageal food impaction"],
    "餐后高血糖": ["postprandial hyperglycemia"],
    "骨佩吉特病": ["paget's disease of bone"],
    "骨关节炎": ["osteoarthritis"],
    "骨关节炎疼痛": ["osteoarthritis pain"],
    "骨和关节感染": ["bone and joint infection"],
    "骨巨细胞瘤": ["giant cell tumor of bone"],
    "骨感染": ["bone infection"],
    "骨折不愈合": ["fracture nonunion"],
    "骨硬化症": ["osteopetrosis"],
    "骨质流失": ["bone loss"],
    "骨质疏松治疗": ["osteoporosis treatment"],
    "骨质疏松症": ["osteoporosis"],
    "骨质疏松预防": ["osteoporosis prevention"],
    "骨转移": ["bone metastases"],
    "骨软化症": ["osteomalacia"],
    "骨髓增生异常/骨髓增殖性疾病": ["myelodysplastic/myeloproliferative diseases"],
    "骨髓增生异常综合征": ["myelodysplastic syndrome"],
    "骨髓炎": ["osteomyelitis"],
    "骨髓纤维化": ["myelofibrosis"],
    "髋关节置换术后静脉血栓栓塞预防": ["venous thromboembolism prophylaxis after hip replacement"],
    "高催乳素血症": ["hyperprolactinemia"],
    "高危女性乳腺癌预防": ["prevention of breast cancer in high-risk women"],
    "高原病": ["altitude sickness"],
    "高同型半胱氨酸血症": ["hyperhomocysteinemia"],
    "高尿酸尿症中复发性草酸钙结石": ["recurrent calcium oxalate stones in hyperuricosuria"],
    "高度微卫星不稳定性癌症": ["microsatellite instability-high cancer"],
    "高甘油三酯血症": ["hypertriglyceridemia"],
    "高眼压症": ["ocular hypertension"],
    "高磷血症": ["hyperphosphatemia"],
    "高胆固醇血症": ["hypercholesterolemia"],
    "高脂血症": ["hyperlipidemia"],
    "高血压": ["hypertension"],
    "高血压伴左心室肥厚患者的卒中风险降低": ["stroke risk reduction in hypertension with left ventricular hypertrophy"],
    "高血压危象": ["hypertensive crisis"],
    "高血压急症": ["hypertensive emergencies", "hypertensive emergency"],
    "高钙尿症": ["hypercalciuria"],
    "高钙血症": ["hypercalcemia"],
    "高钾血症": ["hyperkalemia"],
    "鱼鳞病": ["ichthyosis"],
    "鸟分枝杆菌复合体感染": ["mycobacterium avium complex"],
    "鸟分枝杆菌复合体感染治疗": ["mycobacterium avium complex infection treatment"],
    "鸟分枝杆菌复合体感染预防": ["mycobacterium avium complex infection prophylaxis"],
    "鸟粪石肾结石": ["struvite kidney stone"],
    "鸟胞内分枝杆菌复合体感染": ["mycobacterium avium complex infection"],
    "鸡眼": ["corns"],
    "鸡眼和胼胝": ["corns and calluses"],
    "麻醉": ["anesthesia"],
    "麻醉前镇静": ["preanesthetic sedation"],
    "麻醉维持": ["maintenance of anesthesia"],
    "麻醉诱导": ["induction of anesthesia"],
    "麻醉诱导/维持": ["induction/maintenance of anesthesia"],
    "麻风病": ["leprosy"],
    "麻风结节性红斑": ["erythema nodosum leprosum"],
    "黄褐斑": ["melasma"],
    "黏膜炎": ["mucositis"],
    "黏膜炎疼痛": ["mucositis pain (mouthwash)", "mucositis pain"],
    "黑色素瘤": ["melanoma", "melanoma (adjuvant)"],
    "鼠疫": ["plague"],
    "鼻塞": ["nasal congestion"],
    "鼻息肉": ["nasal polyps"],
    "鼻窦充血": ["sinus congestion"],
    "鼻窦压迫感": ["sinus pressure"],
    "鼻窦炎": ["sinusitis"],
    "鼻腔MRSA去定植": ["nasal mrsa decolonization"],
    "齐多夫定治疗的HIV患者贫血": ["anemia in zidovudine-treated hiv patients"],
}

# ── 中文症状名 → 关联英文疾病名 ──
# 症状不是疾病本身，但可以关联到可能的疾病

SYMPTOM_TO_DISEASE: Dict[str, List[str]] = {
    # 常见症状 → 直接英文症状名 + 1-2个高概率关联疾病
    # 不映射到过于宽泛的类别（如"bacterial infection"、"viral infection"）
    "发烧": ["fever", "influenza"],
    "发热": ["fever", "influenza"],
    "头疼": ["headache", "migraine"],
    "头痛": ["headache", "migraine"],
    "想吐": ["nausea"],
    "恶心": ["nausea"],
    "呕吐": ["vomiting"],
    "拉肚子": ["diarrhea"],
    "腹泻": ["diarrhea"],
    "咳嗽": ["cough", "upper respiratory infection"],
    "干咳": ["cough"],
    "咳痰": ["cough", "bronchitis"],
    "喘": ["asthma", "wheezing"],
    "喘息": ["asthma", "wheezing"],
    "胸闷": ["chest tightness", "angina"],
    "胸痛": ["chest pain", "angina"],
    "心慌": ["palpitation", "arrhythmia"],
    "心悸": ["palpitation", "arrhythmia"],
    "气短": ["shortness of breath", "dyspnea"],
    "呼吸困难": ["dyspnea", "shortness of breath"],
    "头晕": ["dizziness", "vertigo"],
    "眩晕": ["vertigo", "dizziness"],
    "乏力": ["fatigue"],
    "疲倦": ["fatigue"],
    "无力": ["weakness"],
    "水肿": ["edema"],
    "脚肿": ["edema", "peripheral edema"],
    "腿肿": ["edema", "peripheral edema"],
    "肚子疼": ["abdominal pain", "stomach pain"],
    "腹痛": ["abdominal pain"],
    "胃痛": ["stomach pain", "gastritis"],
    "胃疼": ["stomach pain", "gastritis"],
    "反酸": ["acid reflux", "gastroesophageal reflux disease"],
    "烧心": ["heartburn", "gastroesophageal reflux disease"],
    "关节疼": ["joint pain", "arthralgia"],
    "关节痛": ["joint pain", "arthralgia"],
    "腰疼": ["back pain", "low back pain"],
    "腰痛": ["back pain", "low back pain"],
    "肌肉酸痛": ["myalgia", "muscle pain"],
    "肌肉痛": ["myalgia", "muscle pain"],
    "抽筋": ["cramp", "muscle cramp"],
    "皮疹": ["rash", "dermatitis"],
    "痒": ["pruritus", "itching"],
    "皮肤瘙痒": ["pruritus", "itching"],
    "起痘": ["acne vulgaris", "acne"],
    "过敏": ["allergic rhinitis", "allergy"],
    "眼睛痒": ["ocular itching", "allergic conjunctivitis"],
    "流泪": ["tearing", "lacrimation"],
    "鼻塞": ["nasal congestion", "allergic rhinitis"],
    "流鼻涕": ["rhinorrhea", "runny nose", "allergic rhinitis"],
    "打喷嚏": ["sneezing", "allergic rhinitis"],
    "尿频": ["urinary frequency", "urinary tract infection"],
    "尿急": ["urinary urgency", "urinary tract infection"],
    "尿痛": ["dysuria", "urinary tract infection"],
    "血尿": ["hematuria", "urinary tract infection"],
    "失眠": ["insomnia", "sleep disorder"],
    "睡不着": ["insomnia", "sleep disorder"],
    "多梦": ["sleep disorder"],
    "焦虑不安": ["anxiety disorder", "generalized anxiety disorder"],
    "情绪低落": ["depression", "major depressive disorder"],
    "烦躁": ["irritability", "anxiety disorder"],
    "手抖": ["tremor", "essential tremor"],
    "震颤": ["tremor"],
    "麻木": ["numbness", "paresthesia"],
    "刺痛": ["tingling", "paresthesia"],
    "耳鸣": ["tinnitus"],
    "听力下降": ["hearing loss"],
    "视力模糊": ["blurred vision"],
    "口干": ["dry mouth", "xerostomia"],
    "口渴": ["polydipsia", "thirst"],
    "食欲不振": ["anorexia", "loss of appetite"],
    "吃不下": ["anorexia", "loss of appetite"],
    "体重下降": ["weight loss"],
    "消瘦": ["weight loss"],
    "体重增加": ["weight gain"],
    "发胖": ["weight gain"],
}

# ── 英文疾病名标准化映射 (扩充版) ──
# 补充 clinical_matcher.py 之外的常见输入

ENGLISH_DISEASE_EXPAND: Dict[str, List[str]] = {
    "fever": ["fever", "pyrexia", "febrile illness"],
    "headache": ["headache", "cephalalgia", "head pain", "migraine", "tension headache"],
    "pain": ["pain", "ache", "aching", "painful condition"],
    "inflammation": ["inflammation", "inflammatory condition"],
    "diabetes": ["diabetes mellitus", "diabetes", "type 2 diabetes"],
    "hypertension": ["hypertension", "high blood pressure", "htn"],
    "infection": ["infection", "bacterial infection", "viral infection"],
    "cold": ["upper respiratory infection", "common cold", "upper respiratory tract infection"],
    "flu": ["influenza", "flu"],
    "cough": ["cough", "productive cough", "dry cough"],
    "nausea": ["nausea", "vomiting", "emesis"],
    "rash": ["rash", "dermatitis", "skin eruption"],
    "allergy": ["allergic rhinitis", "allergy", "allergic reaction", "allergic dermatitis", "atopic dermatitis"],
    "insomnia": ["insomnia", "sleep disorder"],
    "anxiety": ["anxiety disorder", "generalized anxiety disorder", "anxiety"],
    "depression": ["major depressive disorder", "depression", "depressive disorder"],
    "asthma": ["asthma", "bronchial asthma", "asthma exacerbation"],
    "copd": ["chronic obstructive pulmonary disease", "copd", "copd exacerbation"],
    "obesity": ["obesity", "overweight"],
    "gout": ["gout", "gouty arthritis", "hyperuricemia"],
    "acne": ["acne vulgaris", "acne"],
    "sinusitis": ["sinusitis", "acute bacterial sinusitis", "chronic sinusitis"],
    "gerd": ["gastroesophageal reflux disease", "gerd", "acid reflux", "heartburn"],
    "acid reflux": ["acid reflux", "gastroesophageal reflux disease", "gerd", "heartburn"],
    "ckd": ["chronic kidney disease", "ckd", "renal disease", "renal impairment", "kidney disease"],
    "diverticulitis": ["diverticulitis", "diverticulitis of gastrointestinal tract"],
    "adenocarcinoma": ["adenocarcinoma", "adenocarcinoma of pancreas", "pancreatic cancer"],
}


def translate_chinese_disease(chinese_name: str) -> List[str]:
    """中文疾病名 → 英文标准化名列表

    Args:
        chinese_name: 中文疾病名（如"发烧"、"高血压"）

    Returns:
        英文标准化名列表（如["fever", "pyrexia"]）
    """
    name = chinese_name.strip()
    if not name:
        return []

    # 直接匹配
    if name in CHINESE_TO_ENGLISH_DISEASE:
        return CHINESE_TO_ENGLISH_DISEASE[name]

    # 子串匹配（仅cn_key在name中的方向，且cn_key>=2字符）
    # 不使用name-in-cn_key方向（防止短输入如"风"匹配"痛风"）
    results = []
    for cn_key, en_values in CHINESE_TO_ENGLISH_DISEASE.items():
        if len(cn_key) >= 2 and cn_key in name:
            results.extend(en_values)

    return results


def expand_symptoms_to_diseases(symptom_str: str) -> List[str]:
    """症状 → 关联疾病名列表

    Args:
        symptom_str: 中文症状描述（如"头疼，发烧，想吐"）

    Returns:
        关联的英文疾病名列表
    """
    if not symptom_str:
        return []

    results = []
    # 分割症状（支持中文逗号、英文逗号、空格）
    symptoms = _split_input(symptom_str)

    for symptom in symptoms:
        symptom = symptom.strip()
        if not symptom:
            continue

        # 直接匹配
        if symptom in SYMPTOM_TO_DISEASE:
            results.extend(SYMPTOM_TO_DISEASE[symptom])
        else:
            # 子串匹配（仅s_key在symptom方向，且s_key>=2字符）
            # 不使用symptom-in-s_key方向（防止短输入如"痛"匹配大量疾病）
            for s_key, diseases in SYMPTOM_TO_DISEASE.items():
                if len(s_key) >= 2 and s_key in symptom:
                    results.extend(diseases)

    # 去重
    return list(set(results))


def expand_english_disease(english_name: str) -> List[str]:
    """英文疾病名扩充 → 更多相关英文名

    Args:
        english_name: 英文疾病名（如"fever"、"diabetes"）

    Returns:
        扩充后的英文名列表
    """
    name = english_name.strip().lower()
    if not name:
        return []

    # 直接匹配
    if name in ENGLISH_DISEASE_EXPAND:
        # 保留原始名 + 扩充名（防止丢失如"neuropathic pain"→只有"pain"）
        expanded = ENGLISH_DISEASE_EXPAND[name]
        if name not in expanded:
            return [name] + expanded
        return expanded

    # Word-boundary子串匹配 — 防止"flu"匹配"acid reflux"(因为reflux含flu)
    # 关键改进: 必须保留原始名，防止"neuropathic pain"→只有"pain"的扩充
    import re as _re
    results = [name]  # 始终保留原始名
    for en_key, en_values in ENGLISH_DISEASE_EXPAND.items():
        # 仅当en_key是name的子组件（en_key出现在name中）时才扩充
        # 不再使用反向匹配（name出现在en_key中），因为反向匹配会
        # 让"pain"扩充"neuropathic pain"的值——这是错误的
        if len(en_key) >= 4 and _re.search(r'\b' + _re.escape(en_key) + r'\b', name):
            results.extend(en_values)

    return list(set(results))


def _split_input(text: str) -> List[str]:
    """分割输入字符串（支持中英文逗号、顿号、空格、分号、斜杠）

    Args:
        text: 原始输入文本

    Returns:
        分割后的列表
    """
    import re
    # 支持: 中文逗号，英文逗号, 顿号、, 分号;, 空格, 斜杠/, 全角空格
    parts = re.split(r'[，,;；、/／]+', text)
    return [p.strip() for p in parts if p.strip()]


def process_patient_input(
    diseases_str: str,
    symptoms_str: str,
) -> Set[str]:
    """处理患者输入 → 综合英文疾病名集合

    综合考虑:
    1. 中文疾病名 → 英文
    2. 英文疾病名 → 扩充
    3. 中文症状 → 关联疾病

    Args:
        diseases_str: 疾病描述字符串（中英文混合）
        symptoms_str: 症状描述字符串（中文）

    Returns:
        英文标准化疾病名集合（用于适应症匹配）
    """
    result: Set[str] = set()

    # 1. 处理疾病
    if diseases_str:
        disease_parts = _split_input(diseases_str)
        for part in disease_parts:
            # 尝试中文→英文映射
            en_names = translate_chinese_disease(part)
            if en_names:
                result.update(en_names)
            else:
                # 可能是英文输入，做扩充
                expanded = expand_english_disease(part)
                result.update(expanded)

    # 2. 处理症状 → 关联疾病
    if symptoms_str:
        symptom_diseases = expand_symptoms_to_diseases(symptoms_str)
        result.update(symptom_diseases)

    return result


# ── KnowledgeRouter Integration ──

from app.utils.knowledge_router import get_router


def get_disease_routing_info(chinese_disease: str) -> dict:
    """Get clinical routing information for a disease.

    Returns the full L1->L2->L3 routing trace plus drug class filter.
    Used by the recommendation pipeline to constrain candidate drugs.
    """
    router = get_router()
    return router.route(chinese_disease)


def get_appropriate_drug_classes(chinese_diseases: list) -> set:
    """Get the set of appropriate drug classes for a list of diseases.

    Returns empty set if no drug class filter is possible.
    """
    router = get_router()
    all_classes = set()
    for disease in chinese_diseases:
        classes = router.get_drug_class_filter(str(disease))
        all_classes.update(classes)
    return all_classes